#define _UIAPPIPCAM_Param_C
#include <stdio.h>
#include "Debug.h"
#include "PrjCfg.h"
#include "UIAppIPCam_Param.h"
#include "ImageApp_IPCam.h"
#include "ImageUnit_AudEnc.h"
#include "ImageUnit_AudDec.h"
#include "Audio.h"
///////////////////////////////////////////////////////////////////////////////
#define __MODULE__          UIAppIPCamParam
#define __DBGLVL__          2 // 0=FATAL, 1=ERR, 2=WRN, 3=UNIT, 4=FUNC, 5=IND, 6=MSG, 7=VALUE, 8=USER
#define __DBGFLT__          "*" //*=All, [mark]=CustomClass
#include "DebugModule.h"
///////////////////////////////////////////////////////////////////////////////


#ifndef IPCAM_MD_PATH
#define IPCAM_MD_PATH 2
#endif

#if (IPCAM_MAIN_ON_OFF==0)
	#define IPCAM_MAIN_STREAM_STATE 	IPCAM_STATE_DISABLE
#else
	#define IPCAM_MAIN_STREAM_STATE 	IPCAM_STATE_ENABLE
#endif

#if IPCAM_SUB1_ON_OFF==0
	#define IPCAM_SUB1_STREAM_STATE 	IPCAM_STATE_DISABLE
#else
	#define IPCAM_SUB1_STREAM_STATE 	IPCAM_STATE_ENABLE
#endif

#if IPCAM_SUB2_ON_OFF==0
	#define IPCAM_SUB2_STREAM_STATE 	IPCAM_STATE_DISABLE
#else
	#define IPCAM_SUB2_STREAM_STATE 	IPCAM_STATE_ENABLE
#endif

#if IPCAM_SUB3_ON_OFF==0
	#define IPCAM_SUB3_STREAM_STATE 	IPCAM_STATE_DISABLE
#else
	#define IPCAM_SUB3_STREAM_STATE 	IPCAM_STATE_ENABLE
#endif

#if IPCAM_DISP_ON_OFF==0
	#define IPCAM_DISP_STREAM_STATE 	IPCAM_STATE_DISABLE
#else
	#define IPCAM_DISP_STREAM_STATE 	IPCAM_STATE_ENABLE
#endif

#if (SENSOR2_MAIN_ON_OFF==0)
	#define SENSOR2_MAIN_STREAM_STATE 	IPCAM_STATE_DISABLE
#else
	#define SENSOR2_MAIN_STREAM_STATE 	IPCAM_STATE_ENABLE
#endif

#if SENSOR2_SUB1_ON_OFF==0
	#define SENSOR2_SUB1_STREAM_STATE 	IPCAM_STATE_DISABLE
#else
	#define SENSOR2_SUB1_STREAM_STATE 	IPCAM_STATE_ENABLE
#endif

#if SENSOR2_SUB2_ON_OFF==0
	#define SENSOR2_SUB2_STREAM_STATE 	IPCAM_STATE_DISABLE
#else
	#define SENSOR2_SUB2_STREAM_STATE 	IPCAM_STATE_ENABLE
#endif

//static ISF_PORT_STATE g_sVdoOutStatus = ISF_PORT_STATE_READY;

#if ((IPCAM_FTG_FUNC == ENABLE) || (IPCAM_ODT_FUNC == ENABLE))
#define IPCAM_ALG_COUNT				    2		//FD or FTD needs more than 2 buffers (width need over 832 better)
#else
#define IPCAM_ALG_COUNT				    0
#endif

#if defined(_BSP_NA51023_)
#if (IPCAM_DIS_COMP_FUNC == ENABLE)
#define IPCAM_IPL_COMP				(1)
#else
#define IPCAM_IPL_COMP				(0)
#endif
#else
#define IPCAM_IPL_COMP				(0)
#endif

//Note: IPCAM_IPL_3DNR buffer is located at IPL internal
#if (IPCAM_MAIN_ONE_BUFFER == ENABLE)
#if ((IPCAM_IPL_3DNR == ENABLE) && (IPCAM_MAIN_WIDTH>2592))
#define IPCAM_MAIN_COUNT (2)
#else
#define IPCAM_MAIN_COUNT (1)
#endif
#else
#define IPCAM_MAIN_COUNT				(IPCAM_MAIN_WAIT + (IPCAM_MAIN_TRIGGER != IPCAM_TRIGGER_DEST) + IPCAM_IPL_DIRECT + IPCAM_IPL_COMP + 2/*for cv func*/)
#endif

#if (IPCAM_DISP_ONE_BUFFER == ENABLE)
#define IPCAM_DISP_COUNT				(1)
#else
#define IPCAM_DISP_COUNT				(1 + IPCAM_DISP_WAIT + (IPCAM_DISP_TRIGGER != IPCAM_TRIGGER_DEST) + IPCAM_IPL_DIRECT + IPCAM_IPL_COMP)
#endif

#if (IPCAM_SUB1_ONE_BUFFER == ENABLE)
#define IPCAM_SUB1_COUNT				(1)
#else
#define IPCAM_SUB1_COUNT				(2 + IPCAM_IPL_DIRECT + IPCAM_ALG_COUNT + IPCAM_IPL_COMP)  //ping-pong buffer
#endif

#define IPCAM_SUB2_COUNT				(2 + IPCAM_IPL_DIRECT + IPCAM_IPL_COMP)   //ping-pong buffer
#define IPCAM_SUB3_COUNT				(2 + IPCAM_IPL_DIRECT + IPCAM_IPL_COMP)   //ping-pong buffer

//Secondary Sensor Config
#define SENSOR2_MAIN_COUNT				IPCAM_MAIN_COUNT
#define SENSOR2_SUB1_COUNT				IPCAM_SUB1_COUNT
#define SENSOR2_SUB2_COUNT				IPCAM_SUB2_COUNT

static UIAPPIPCAM_BLOCK_BUFFER_INFO g_UIAppIPCamBlockBufferInfo[NVTMPP_VB_MAX_COMM_POOLS] = {
	    //  isEnabled,                      sResolution,             count,           ddr, compress, default format
#if (IPCAM_SMARTROI_FUNC == ENABLE)
		{ IPCAM_MAIN_ON_OFF,   { IPCAM_MAIN_WIDTH,   IPCAM_MAIN_HEIGHT},   IPCAM_MAIN_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
		{ IPCAM_DISP_ON_OFF,   { IPCAM_DISP_WIDTH,   IPCAM_DISP_HEIGHT},   IPCAM_DISP_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
		{ IPCAM_SUB1_ON_OFF,   { IPCAM_SUB1_WIDTH,   IPCAM_SUB1_HEIGHT},   IPCAM_SUB1_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
		{ IPCAM_SUB2_ON_OFF,   { IPCAM_SUB2_WIDTH,   IPCAM_SUB2_HEIGHT},   IPCAM_SUB2_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
		{ IPCAM_SUB3_ON_OFF,   { IPCAM_SUB3_WIDTH,   IPCAM_SUB3_HEIGHT},   IPCAM_SUB3_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
		{ SENSOR2_MAIN_ON_OFF, { SENSOR2_MAIN_WIDTH, SENSOR2_MAIN_HEIGHT}, SENSOR2_MAIN_COUNT, NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
		{ SENSOR2_SUB1_ON_OFF, { SENSOR2_SUB1_WIDTH, SENSOR2_SUB1_HEIGHT}, SENSOR2_SUB1_COUNT, NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
		{ SENSOR2_SUB2_ON_OFF, { SENSOR2_SUB2_WIDTH, SENSOR2_SUB2_HEIGHT}, SENSOR2_SUB2_COUNT, NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
#else
		{ IPCAM_MAIN_ON_OFF,   { IPCAM_MAIN_WIDTH,   IPCAM_MAIN_HEIGHT},   IPCAM_MAIN_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
	#if (IPCAM_MD_PATH == 1)
		{ IPCAM_DISP_ON_OFF,   { IPCAM_DISP_WIDTH,   IPCAM_DISP_HEIGHT},   IPCAM_DISP_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
		{ IPCAM_SUB1_ON_OFF,   { IPCAM_SUB1_WIDTH,   IPCAM_SUB1_HEIGHT},   IPCAM_SUB1_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
	#else
		{ IPCAM_DISP_ON_OFF,   { IPCAM_DISP_WIDTH,   IPCAM_DISP_HEIGHT},   IPCAM_DISP_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ IPCAM_SUB1_ON_OFF,   { IPCAM_SUB1_WIDTH,   IPCAM_SUB1_HEIGHT},   IPCAM_SUB1_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
	#endif
		{ IPCAM_SUB2_ON_OFF,   { IPCAM_SUB2_WIDTH,   IPCAM_SUB2_HEIGHT},   IPCAM_SUB2_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ IPCAM_SUB3_ON_OFF,   { IPCAM_SUB3_WIDTH,   IPCAM_SUB3_HEIGHT},   IPCAM_SUB3_COUNT,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ SENSOR2_MAIN_ON_OFF, { SENSOR2_MAIN_WIDTH, SENSOR2_MAIN_HEIGHT}, SENSOR2_MAIN_COUNT, NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ SENSOR2_SUB1_ON_OFF, { SENSOR2_SUB1_WIDTH, SENSOR2_SUB1_HEIGHT}, SENSOR2_SUB1_COUNT, NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420_MD},
		{ SENSOR2_SUB2_ON_OFF, { SENSOR2_SUB2_WIDTH, SENSOR2_SUB2_HEIGHT}, SENSOR2_SUB2_COUNT, NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
#endif

		{ FALSE, { 1920,  1088},   3,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ FALSE, { 1920,  1088},   3,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ FALSE, { 1920,  1088},   3,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ FALSE, { 1920,  1088},   3,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ FALSE, { 1920,  1088},   3,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ FALSE, { 1920,  1088},   3,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ FALSE, { 1920,  1088},   3,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
		{ FALSE, { 1920,  1088},   3,   NVTMPP_DDR_1, FALSE,  IPCAM_FMT_420},
};


static IPCAM_STREAM_INFO g_ImageAppStreamInfo[IPCAM_PATH_MAX_ID] = {
	{IPCAM_PATH_ID_0, IPCAM_MAIN_STREAM_STATE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_MAIN, IPCAM_MAIN_TRIGGER, IPCAM_MAIN_COUNT},
	{IPCAM_PATH_ID_1, IPCAM_DISP_STREAM_STATE, IPCAM_SENSOR1, IPCAM_IME2, IPCAM_STREAM_MAIN, IPCAM_DISP_TRIGGER, IPCAM_DISP_COUNT},
	{IPCAM_PATH_ID_2, IPCAM_SUB1_STREAM_STATE, IPCAM_SENSOR1, IPCAM_IME3, IPCAM_STREAM_MAIN, IPCAM_SUB1_TRIGGER, IPCAM_SUB1_COUNT},
	{IPCAM_PATH_ID_3, IPCAM_SUB2_STREAM_STATE, IPCAM_SENSOR1, IPCAM_IME2, IPCAM_STREAM_MAIN, IPCAM_TRIGGER_SRC, IPCAM_SUB2_COUNT},
	{IPCAM_PATH_ID_4, IPCAM_SUB3_STREAM_STATE, IPCAM_SENSOR1, IPCAM_IME2, IPCAM_STREAM_EXT, IPCAM_TRIGGER_SRC, IPCAM_SUB3_COUNT},
	{IPCAM_PATH_ID_5, SENSOR2_MAIN_STREAM_STATE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_MAIN, IPCAM_MAIN_TRIGGER, IPCAM_MAIN_COUNT},
	{IPCAM_PATH_ID_6, SENSOR2_SUB1_STREAM_STATE, IPCAM_SENSOR1, IPCAM_IME3, IPCAM_STREAM_MAIN, IPCAM_SUB1_TRIGGER, IPCAM_SUB1_COUNT},
	{IPCAM_PATH_ID_7, SENSOR2_SUB2_STREAM_STATE, IPCAM_SENSOR1, IPCAM_IME2, IPCAM_STREAM_MAIN, IPCAM_TRIGGER_SRC, IPCAM_SUB2_COUNT},
#if defined(_BSP_NA51000_)
	{IPCAM_PATH_ID_8, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT, IPCAM_TRIGGER_SRC, 0},
	{IPCAM_PATH_ID_9, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT, IPCAM_TRIGGER_SRC, 0},
	{IPCAM_PATH_ID_10, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT, IPCAM_TRIGGER_SRC, 0},
	{IPCAM_PATH_ID_11, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT, IPCAM_TRIGGER_SRC, 0},
	{IPCAM_PATH_ID_12, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT, IPCAM_TRIGGER_SRC, 0},
	{IPCAM_PATH_ID_13, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT, IPCAM_TRIGGER_SRC, 0},
	{IPCAM_PATH_ID_14, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME1, IPCAM_STREAM_EXT, IPCAM_TRIGGER_SRC, 0},
	{IPCAM_PATH_ID_15, IPCAM_STATE_DISABLE, IPCAM_SENSOR1, IPCAM_IME5, IPCAM_STREAM_EXT, IPCAM_TRIGGER_SRC, 0}
#endif
};

static UIAPPIPCAM_SENSOR_INFO g_UIAppIPCamSensorInfo[UIAPPIPCAM_SENSOR_MAX] = {

	//sensor ID,  IPL fps, IPL ratio, flip type, IME 3DNR , video format[ime_out], video compress,crop enable
	{UIAPPIPCAM_SENSOR1, IPCAM_IN_FPS,{IPCAM_OUT_FPS,IPCAM_OUT_FPS,IPCAM_OUT_FPS,IPCAM_OUT_FPS,IPCAM_OUT_FPS}, IPCAM_ASPECT_RATIO, FLIP_NONE, IPCAM_IPL_3DNR,   {IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_Y, IPCAM_FMT_422}, FALSE, {FALSE,FALSE,FALSE,FALSE,FALSE}},
	{UIAPPIPCAM_SENSOR2, IPCAM_IN_FPS,{IPCAM_OUT_FPS,IPCAM_OUT_FPS,IPCAM_OUT_FPS,IPCAM_OUT_FPS,IPCAM_OUT_FPS}, IPCAM_ASPECT_RATIO, FLIP_NONE, IPCAM_IPL_3DNR,   {IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_Y, IPCAM_FMT_422}, FALSE, {FALSE,FALSE,FALSE,FALSE,FALSE}},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_SENSOR3, 25,{25,25,25,25,25}, {16, 9}, FLIP_NONE, FALSE,   {IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_Y, IPCAM_FMT_422}, FALSE, {FALSE,FALSE,FALSE,FALSE,FALSE}},
	{UIAPPIPCAM_SENSOR4, 25,{25,25,25,25,25}, {16, 9}, FLIP_NONE, FALSE,  {IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_Y, IPCAM_FMT_422}, FALSE, {FALSE,FALSE,FALSE,FALSE,FALSE}},
	{UIAPPIPCAM_SENSOR5, 25,{25,25,25,25,25}, {16, 9}, FLIP_NONE, FALSE,  {IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_Y, IPCAM_FMT_422}, FALSE, {FALSE,FALSE,FALSE,FALSE,FALSE}},
	{UIAPPIPCAM_SENSOR6, 25,{25,25,25,25,25}, {16, 9}, FLIP_NONE, FALSE,  {IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_Y, IPCAM_FMT_422}, FALSE, {FALSE,FALSE,FALSE,FALSE,FALSE}},
	{UIAPPIPCAM_SENSOR7, 25,{25,25,25,25,25}, {16, 9}, FLIP_NONE, FALSE,  {IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_Y, IPCAM_FMT_422}, FALSE, {FALSE,FALSE,FALSE,FALSE,FALSE}},
	{UIAPPIPCAM_SENSOR8, 25,{25,25,25,25,25}, {16, 9}, FLIP_NONE, FALSE,  {IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_420, IPCAM_FMT_Y, IPCAM_FMT_422}, FALSE, {FALSE,FALSE,FALSE,FALSE,FALSE}}
#endif
};


static UIAPPIPCAM_CROP_INFO g_UIAppIPCamCropInfo[UIAPPIPCAM_SENSOR_MAX]={
	// sensor ID        ,{IME1 crop, IME2 crop,IME3 crop,IME4 crop,IME5 crop}
	{UIAPPIPCAM_SENSOR1, {{0,0},{0,0},{0,0},{0,0},{0,0}}, {{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
	{UIAPPIPCAM_SENSOR2, {{0,0},{0,0},{0,0},{0,0},{0,0}}, {{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_SENSOR3, {{0,0},{0,0},{0,0},{0,0},{0,0}}, {{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
	{UIAPPIPCAM_SENSOR4, {{0,0},{0,0},{0,0},{0,0},{0,0}}, {{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
	{UIAPPIPCAM_SENSOR5, {{0,0},{0,0},{0,0},{0,0},{0,0}}, {{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
	{UIAPPIPCAM_SENSOR6, {{0,0},{0,0},{0,0},{0,0},{0,0}}, {{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
	{UIAPPIPCAM_SENSOR7, {{0,0},{0,0},{0,0},{0,0},{0,0}}, {{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
	{UIAPPIPCAM_SENSOR8, {{0,0},{0,0},{0,0},{0,0},{0,0}}, {{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}}
#endif
};

static UIAPPIPCAM_ENCODE_CONFIG g_UIAppIPCamEncodeConfig[UIAPPIPCAM_PATH_MAX_ID] = {

//*****The value about targit bitrate, GOP ,FPS must be the same with CBR (g_UIAppIPCamCBRConFig) or VBR (g_UIAppIPCamVBRConFig) structure ***//

	//ID             , size            ,   codec         ,encode 3DNR, BRC type,  rotate type, svc type,  LTR, SEI
#if (_FPGA_EMULATION_ == ENABLE)
	{UIAPPIPCAM_PATH_ID_0, {960, 240}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_1, {480, 120}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_2, {320, 240}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_3, {1920, 1080}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_4, {1920, 1080}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
#else
//set VDOENC_PARAM_USRQP parm if the path has md data
#if (IPCAM_SMARTROI_FUNC == ENABLE)
	{UIAPPIPCAM_PATH_ID_0, {IPCAM_MAIN_WIDTH, IPCAM_MAIN_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},TRUE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_1, {IPCAM_DISP_WIDTH, IPCAM_DISP_HEIGHT}, IPCAMCODEC_H265, {FALSE},          UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_2, {IPCAM_SUB1_WIDTH, IPCAM_SUB1_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},TRUE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_3, {IPCAM_SUB2_WIDTH, IPCAM_SUB2_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},TRUE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_4, {IPCAM_SUB3_WIDTH, IPCAM_SUB3_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},TRUE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_5, {SENSOR2_MAIN_WIDTH, SENSOR2_MAIN_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},TRUE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_6, {SENSOR2_SUB1_WIDTH, SENSOR2_SUB1_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},TRUE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_7, {SENSOR2_SUB2_WIDTH, SENSOR2_SUB2_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},TRUE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
#else
	{UIAPPIPCAM_PATH_ID_0, {IPCAM_MAIN_WIDTH, IPCAM_MAIN_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{TRUE}},
	{UIAPPIPCAM_PATH_ID_1, {IPCAM_DISP_WIDTH, IPCAM_DISP_HEIGHT}, IPCAMCODEC_H265, {FALSE},          UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_2, {IPCAM_SUB1_WIDTH, IPCAM_SUB1_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{TRUE}},
	{UIAPPIPCAM_PATH_ID_3, {IPCAM_SUB2_WIDTH, IPCAM_SUB2_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{TRUE}},
	{UIAPPIPCAM_PATH_ID_4, {IPCAM_SUB3_WIDTH, IPCAM_SUB3_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_5, {SENSOR2_MAIN_WIDTH, SENSOR2_MAIN_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_6, {SENSOR2_SUB1_WIDTH, SENSOR2_SUB1_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
	{UIAPPIPCAM_PATH_ID_7, {SENSOR2_SUB2_WIDTH, SENSOR2_SUB2_HEIGHT}, IPCAMCODEC_H265, {IPCAM_ENC_3DNR}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH,{FALSE}},
#endif
#endif // end of _FPGA_EMULATION_
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_PATH_ID_8, {1920, 1080}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH},
	{UIAPPIPCAM_PATH_ID_9, {1920, 1080}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH},
	{UIAPPIPCAM_PATH_ID_10, {1920, 1080}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH},
	{UIAPPIPCAM_PATH_ID_11, {1920, 1080}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH},
	{UIAPPIPCAM_PATH_ID_12, {1920, 1080}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH},
	{UIAPPIPCAM_PATH_ID_13, {1920, 1080}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH},
	{UIAPPIPCAM_PATH_ID_14, {1920, 1080}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH},
	{UIAPPIPCAM_PATH_ID_15, {640, 480}, IPCAMCODEC_H265, {FALSE}, UIAPPIPCAM_BRC_CBR, UIAPPIPCAM_RT_NONE, MP_VDOENC_SVC_DISABLE,{0,0},FALSE,MP_VDOENC_PROFILE_HIGH}
#endif
};


static UIAPPIPCAM_CBR_CONFIG g_UIAppIPCamCBRConFig[UIAPPIPCAM_PATH_MAX_ID] = {
	//{  UIAPPIPCAM_PATH_ID,   MP_VDOENC_CBR_INFO }
	{UIAPPIPCAM_PATH_ID_0, {1, 0, IPCAM_MAIN_MAX_BYTES, IPCAM_OUT_FPS, 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_1, {1, 0, 100 * 1024		  , 30			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_2, {1, 0, IPCAM_SUB1_MAX_BYTES, 30			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_3, {1, 0, IPCAM_SUB2_MAX_BYTES, 30			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_4, {1, 0, IPCAM_SUB3_MAX_BYTES, 30			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_5, {1, 0, SENSOR2_MAIN_MAX_BYTES,IPCAM_OUT_FPS,50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_6, {1, 0, SENSOR2_SUB1_MAX_BYTES,30			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_7, {1, 0, SENSOR2_SUB2_MAX_BYTES,30			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_PATH_ID_8, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_9, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_10, {1, 0, 512 * 1024		  , 25		     , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_11, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_12, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_13, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_14, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_15, {1, 0, 512 * 1024		  , 25	         , 50, 26, 15, 45, 26, 15, 45, 0, 1, 4, 2}}
#endif
};


static UIAPPIPCAM_VBR_CONFIG g_UIAppIPCamVBRConFig[UIAPPIPCAM_PATH_MAX_ID] = {
	//{  UIAPPIPCAM_PATH_ID,   MP_VDOENC_VBR_INFO }
	{UIAPPIPCAM_PATH_ID_0, {0, 0, IPCAM_MAIN_MAX_BYTES, IPCAM_OUT_FPS, 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_1, {0, 0, 100 * 1024		  , 30			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_2, {0, 0, IPCAM_SUB1_MAX_BYTES, 30			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_3, {1, 0, IPCAM_SUB2_MAX_BYTES, 30			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_4, {1, 0, IPCAM_SUB3_MAX_BYTES, 30			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_5, {1, 0, SENSOR2_MAIN_MAX_BYTES,IPCAM_OUT_FPS,50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_6, {1, 0, SENSOR2_SUB1_MAX_BYTES,30	 		 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_7, {1, 0, SENSOR2_SUB2_MAX_BYTES,30	 		 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_PATH_ID_8, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_9, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_10, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_11, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_12, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_13, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_14, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}},
	{UIAPPIPCAM_PATH_ID_15, {1, 0, 512 * 1024		  , 25			 , 50, 26, 15, 45, 26, 15, 45, 0, 0, 1, 4, 2}}
#endif
};

static UIAPPIPCAM_BRC_NONE_CONFIG g_UIAppIPCamBRCNoneConFig[UIAPPIPCAM_PATH_MAX_ID] = {
	//{  UIAPPIPCAM_PATH_ID, fps, GOP, target byterate }
	{UIAPPIPCAM_PATH_ID_0, IPCAM_OUT_FPS, 50, IPCAM_MAIN_MAX_BYTES},
	{UIAPPIPCAM_PATH_ID_1, 30, 50, 512 * 1024},
	{UIAPPIPCAM_PATH_ID_2, 30, 50, IPCAM_SUB1_MAX_BYTES},
	{UIAPPIPCAM_PATH_ID_3, 30, 50, IPCAM_SUB2_MAX_BYTES},
	{UIAPPIPCAM_PATH_ID_4, 30, 50, IPCAM_SUB3_MAX_BYTES},
	{UIAPPIPCAM_PATH_ID_5, 30, 50, SENSOR2_MAIN_MAX_BYTES},
	{UIAPPIPCAM_PATH_ID_6, 30, 50, SENSOR2_SUB1_MAX_BYTES},
	{UIAPPIPCAM_PATH_ID_7, 30, 50, SENSOR2_SUB2_MAX_BYTES},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_PATH_ID_8, 25, 50, 512 * 1024},
	{UIAPPIPCAM_PATH_ID_9, 25, 50, 512 * 1024},
	{UIAPPIPCAM_PATH_ID_10, 25, 50, 512 * 1024},
	{UIAPPIPCAM_PATH_ID_11, 25, 50, 512 * 1024},
	{UIAPPIPCAM_PATH_ID_12, 25, 50, 512 * 1024},
	{UIAPPIPCAM_PATH_ID_13, 25, 50, 512 * 1024},
	{UIAPPIPCAM_PATH_ID_14, 25, 50, 512 * 1024},
	{UIAPPIPCAM_PATH_ID_15, 25, 50, 512 * 1024}
#endif
};

static UIAPPIPCAM_EVBR_CONFIG g_UIAppIPCamEVBRConfig[UIAPPIPCAM_PATH_MAX_ID] = {

	{UIAPPIPCAM_PATH_ID_0, {1, 0, IPCAM_MAIN_MAX_BYTES, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_1, {1, 0, 512 * 1024, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_2, {1, 0, IPCAM_SUB1_MAX_BYTES, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_3, {1, 0, IPCAM_SUB2_MAX_BYTES, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_4, {1, 0, IPCAM_SUB3_MAX_BYTES, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_5, {1, 0, SENSOR2_MAIN_MAX_BYTES, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_6, {1, 0, SENSOR2_SUB1_MAX_BYTES, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_7, {1, 0, SENSOR2_SUB2_MAX_BYTES, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_PATH_ID_8, {1, 0, 512 * 1024, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_9, {1, 0, 512 * 1024, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_10, {1, 0, 512 * 1024, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_11, {1, 0, 512 * 1024, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_12, {1, 0, 512 * 1024, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_13, {1, 0, 512 * 1024, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_14, {1, 0, 512 * 1024, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}},
	{UIAPPIPCAM_PATH_ID_15, {1, 0, 512 * 1024, 25, 50, 25, 26, 15, 45, 26, 15, 45, 0, 0, -6, 1, 4, 2, 150, 30, 0, 0, 0}}
#endif
};


static UIAPPIPCAM_FIXQP_CONFIG g_UIAppIPCamFIXQPConFig[UIAPPIPCAM_PATH_MAX_ID] = {
	// path , {MP_VDOENC_FIXQP_INFO}
	{UIAPPIPCAM_PATH_ID_0, {IPCAM_MAIN_MAX_BYTES, IPCAM_OUT_FPS, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_1, {512 * 1024, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_2, {IPCAM_SUB1_MAX_BYTES, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_3, {IPCAM_SUB2_MAX_BYTES, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_4, {IPCAM_SUB3_MAX_BYTES, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_5, {SENSOR2_MAIN_MAX_BYTES, IPCAM_OUT_FPS, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_6, {SENSOR2_SUB1_MAX_BYTES, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_7, {SENSOR2_SUB2_MAX_BYTES, 25, 50, 1, 26, 26}},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_PATH_ID_8, {512 * 1024, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_9, {512 * 1024, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_10, {512 * 1024, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_11, {512 * 1024, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_12, {512 * 1024, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_13, {512 * 1024, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_14, {512 * 1024, 25, 50, 1, 26, 26}},
	{UIAPPIPCAM_PATH_ID_15, {512 * 1024, 25, 50, 1, 26, 26}}
#endif
};

static UIAPPIPCAM_AQ_CONFIG g_UIAppIPCamAQConFig[UIAPPIPCAM_PATH_MAX_ID] = {
	// path , {MP_VDOENC_AQ_INFO}
	{UIAPPIPCAM_PATH_ID_0, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_1, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_2, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_3, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_4, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_5, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_6, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_7, {1, 3, 36, 8, -6, 0}},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_PATH_ID_8, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_9, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_10, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_11, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_12, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_13, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_14, {1, 3, 36, 8, -6, 0}},
	{UIAPPIPCAM_PATH_ID_15, {1, 3, 36, 8, -6, 0}}
#endif
};

#if (IPCAM_DIS_COMP_FUNC == ENABLE)
#define IPL_DIS_FUNC SEL_DISCOMP_ON
#else
#define IPL_DIS_FUNC SEL_DISCOMP_OFF
#endif

static UIAPPIPCAM_IPL_FUNC g_UIAppIPCamIPLFuncConfig[UIAPPIPCAM_SENSOR_MAX]={
     //    sensor ID   ,HDR                                 ,DIS             ,WDR           ,defog
	{UIAPPIPCAM_SENSOR1, {SEL_SHDR_OFF,SEL_SHDR_FRAME_2,512}, IPL_DIS_FUNC,{SEL_WDR_OFF,0},{SEL_DEFOG_OFF,0}},
	{UIAPPIPCAM_SENSOR2, {SEL_SHDR_OFF,SEL_SHDR_FRAME_2,512}, IPL_DIS_FUNC,{SEL_WDR_OFF,0},{SEL_DEFOG_OFF,0}},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_SENSOR3, {SEL_SHDR_OFF,SEL_SHDR_FRAME_2,512}, IPL_DIS_FUNC,{SEL_WDR_OFF,0},{SEL_DEFOG_OFF,0}},
	{UIAPPIPCAM_SENSOR4, {SEL_SHDR_OFF,SEL_SHDR_FRAME_2,512}, IPL_DIS_FUNC,{SEL_WDR_OFF,0},{SEL_DEFOG_OFF,0}},
	{UIAPPIPCAM_SENSOR5, {SEL_SHDR_OFF,SEL_SHDR_FRAME_2,512}, IPL_DIS_FUNC,{SEL_WDR_OFF,0},{SEL_DEFOG_OFF,0}},
	{UIAPPIPCAM_SENSOR6, {SEL_SHDR_OFF,SEL_SHDR_FRAME_2,512}, IPL_DIS_FUNC,{SEL_WDR_OFF,0},{SEL_DEFOG_OFF,0}},
	{UIAPPIPCAM_SENSOR7, {SEL_SHDR_OFF,SEL_SHDR_FRAME_2,512}, IPL_DIS_FUNC,{SEL_WDR_OFF,0},{SEL_DEFOG_OFF,0}},
	{UIAPPIPCAM_SENSOR8, {SEL_SHDR_OFF,SEL_SHDR_FRAME_2,512}, IPL_DIS_FUNC,{SEL_WDR_OFF,0},{SEL_DEFOG_OFF,0}}
#endif
};

static UIAPPIPCAM_VIDEO_MAXCONFIG g_UIAppIPCamVdoMaxBufConfig[UIAPPIPCAM_PATH_MAX_ID] = {
	//path,                codec           , w,					h,					byterate,				bufms, 					 recformat, 		SVC,				LTRInterval,	rotate, snapshot
	{UIAPPIPCAM_PATH_ID_0, IPCAMCODEC_H265, IPCAM_MAIN_WIDTH,	IPCAM_MAIN_HEIGHT,	IPCAM_MAIN_MAX_BYTES,	IPCAM_VDOENC_MAX_BUF_MS ,MEDIAREC_LIVEVIEW,MP_VDOENC_SVC_DISABLE,IPCAM_LONG_TERM_REF_FUNC	,1     ,1},
	{UIAPPIPCAM_PATH_ID_1, IPCAMCODEC_H265, 1280,				720,				512*1024,				IPCAM_VDOENC_MAX_BUF_MS ,MEDIAREC_LIVEVIEW,MP_VDOENC_SVC_DISABLE, 0, 1, 1},
	{UIAPPIPCAM_PATH_ID_2, IPCAMCODEC_H265, IPCAM_SUB1_WIDTH,  IPCAM_SUB1_HEIGHT,	IPCAM_SUB1_MAX_BYTES,	IPCAM_VDOENC_MAX_BUF_MS ,MEDIAREC_LIVEVIEW,MP_VDOENC_SVC_DISABLE,IPCAM_LONG_TERM_REF_FUNC	,1     ,1},
	{UIAPPIPCAM_PATH_ID_3, IPCAMCODEC_H265, IPCAM_SUB2_WIDTH,  IPCAM_SUB2_HEIGHT,	IPCAM_SUB2_MAX_BYTES,	IPCAM_VDOENC_MAX_BUF_MS ,MEDIAREC_LIVEVIEW,MP_VDOENC_SVC_DISABLE,IPCAM_LONG_TERM_REF_FUNC	,1     ,1},
	{UIAPPIPCAM_PATH_ID_4, IPCAMCODEC_H265, IPCAM_SUB3_WIDTH,  IPCAM_SUB3_HEIGHT,	IPCAM_SUB3_MAX_BYTES,	IPCAM_VDOENC_MAX_BUF_MS ,MEDIAREC_LIVEVIEW,MP_VDOENC_SVC_DISABLE,IPCAM_LONG_TERM_REF_FUNC	,1     ,1},
	{UIAPPIPCAM_PATH_ID_5, IPCAMCODEC_H265, SENSOR2_MAIN_WIDTH,SENSOR2_MAIN_HEIGHT,SENSOR2_MAIN_MAX_BYTES,	IPCAM_VDOENC_MAX_BUF_MS ,MEDIAREC_LIVEVIEW,MP_VDOENC_SVC_DISABLE,IPCAM_LONG_TERM_REF_FUNC	,1     ,1},
	{UIAPPIPCAM_PATH_ID_6, IPCAMCODEC_H265, SENSOR2_SUB1_WIDTH,SENSOR2_SUB1_HEIGHT,SENSOR2_SUB1_MAX_BYTES,	IPCAM_VDOENC_MAX_BUF_MS ,MEDIAREC_LIVEVIEW,MP_VDOENC_SVC_DISABLE,IPCAM_LONG_TERM_REF_FUNC	,1     ,1},
	{UIAPPIPCAM_PATH_ID_7, IPCAMCODEC_H265, SENSOR2_SUB2_WIDTH,SENSOR2_SUB2_HEIGHT,SENSOR2_SUB2_MAX_BYTES,	IPCAM_VDOENC_MAX_BUF_MS ,MEDIAREC_LIVEVIEW,MP_VDOENC_SVC_DISABLE,IPCAM_LONG_TERM_REF_FUNC	,1     ,1},
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_PATH_ID_8, IPCAMCODEC_H265,640,480  ,256*1024 ,IPCAM_VDOENC_MAX_BUF_MS     ,MEDIAREC_LIVEVIEW,0   ,0		,1     ,1},
	{UIAPPIPCAM_PATH_ID_9, IPCAMCODEC_H265,640,480  ,256*1024 ,IPCAM_VDOENC_MAX_BUF_MS     ,MEDIAREC_LIVEVIEW,0   ,0		,1     ,1},
	{UIAPPIPCAM_PATH_ID_10, IPCAMCODEC_H265,640,480 ,256*1024 ,IPCAM_VDOENC_MAX_BUF_MS     ,MEDIAREC_LIVEVIEW,0   ,0		,1     ,1},
	{UIAPPIPCAM_PATH_ID_11, IPCAMCODEC_H265,640,480 ,256*1024 ,IPCAM_VDOENC_MAX_BUF_MS     ,MEDIAREC_LIVEVIEW,0   ,0		,1     ,1},
	{UIAPPIPCAM_PATH_ID_12, IPCAMCODEC_H265,640,480 ,256*1024 ,IPCAM_VDOENC_MAX_BUF_MS     ,MEDIAREC_LIVEVIEW,0   ,0		,1     ,1},
	{UIAPPIPCAM_PATH_ID_13, IPCAMCODEC_H265,640,480 ,256*1024 ,IPCAM_VDOENC_MAX_BUF_MS     ,MEDIAREC_LIVEVIEW,0   ,0		,1     ,1},
	{UIAPPIPCAM_PATH_ID_14, IPCAMCODEC_H265,640,480 ,256*1024 ,IPCAM_VDOENC_MAX_BUF_MS     ,MEDIAREC_LIVEVIEW,0   ,0		,1     ,1},
	{UIAPPIPCAM_PATH_ID_15, IPCAMCODEC_H265,640,480 ,256*1024 ,IPCAM_VDOENC_MAX_BUF_MS     ,MEDIAREC_LIVEVIEW,0   ,0		,1     ,1}
#endif
};


static UIAPPIPCAM_IME_SCALE_TYPE g_UIAppIPCamIMEScaleConfig[UIAPPIPCAM_SENSOR_MAX]={
	// sensor ID        ,
	{UIAPPIPCAM_SENSOR1,0x10001,IPL_IME_AUTO,IPL_IME_AUTO },
	{UIAPPIPCAM_SENSOR2,0x10001,IPL_IME_AUTO,IPL_IME_AUTO },
#if defined(_BSP_NA51000_)
	{UIAPPIPCAM_SENSOR3,0x10001,IPL_IME_AUTO,IPL_IME_AUTO },
	{UIAPPIPCAM_SENSOR4,0x10001,IPL_IME_AUTO,IPL_IME_AUTO },
	{UIAPPIPCAM_SENSOR5,0x10001,IPL_IME_AUTO,IPL_IME_AUTO },
	{UIAPPIPCAM_SENSOR6,0x10001,IPL_IME_AUTO,IPL_IME_AUTO },
	{UIAPPIPCAM_SENSOR7,0x10001,IPL_IME_AUTO,IPL_IME_AUTO },
	{UIAPPIPCAM_SENSOR8,0x10001,IPL_IME_AUTO,IPL_IME_AUTO }
#endif
};


char *ProductSensorName = _SENSOR1_;

char *ProductDisplay1Name = _LCD_NAME_;

char *ProductDisplay2Name = _LCD2_NAME_;

char *ProductDisplay3Name = _TV_NAME_;

char *ProductEmbeddedMemoryName = _EMBMEM_NAME_;

char *ProductDSPFeatureName = "Undefined";

static INT32     g_iDisplayPath = IPCAM_DISP_PATH_NO;
static INT32     g_iALGPath = IPCAM_ALG_PATH_NO;
static INT32 	 g_iYUVPath = IPCAM_YUV_PATH_NO;

static WAVSTUD_INFO_SET         g_AudioInMaxInfo = {
	//objCount, dataMode,                audInfo.audSR,                don't care,  audInfo.bitPerSamp,   audInfo.ch_num,             bufCount,                 unitTime
	1,          WAVSTUD_DATA_MODE_PUSH, {IPCAM_AUD_IN_MAX_SAMPLE_RATE, 0,           IPCAM_AUD_IN_MAX_BIT, IPCAM_AUD_IN_MAX_CHANNELS}, IPCAM_AUD_IN_MAX_BUF_CNT, 1
};

static WAVSTUD_INFO_SET         g_AudioOutMaxInfo = {
	1, WAVSTUD_DATA_MODE_PUSH, {IPCAM_AUD_OUT_MAX_SAMPLE_RATE, 0, IPCAM_AUD_OUT_MAX_BIT, IPCAM_AUD_OUT_MAX_CHANNELS}, IPCAM_AUD_OUT_MAX_BUF_CNT, 1
};

static NMI_AUDENC_MAX_MEM_INFO  g_AudioEncMaxInfo = {
	//uiAudCodec,   uiRecFormat,       uiAudChannels,             uiAudioSR                     uiAudBits
	MOVAUDENC_PCM,	MEDIAREC_LIVEVIEW, IPCAM_AUD_IN_MAX_CHANNELS, IPCAM_AUD_IN_MAX_SAMPLE_RATE, IPCAM_AUD_IN_MAX_BIT, 0, 0
};

static NMI_AUDDEC_MAX_MEM_INFO  g_AudioDecMaxInfo = {
	//uiAudCodec,        uiAudChannels,             uiAudioSR
	AUDDEC_DECODER_ULAW, IPCAM_AUD_IN_MAX_CHANNELS, IPCAM_AUD_IN_MAX_SAMPLE_RATE, 0, 0
};

static STMRCV_MAX_MEM_INFO g_StreamReceiverMaxInfo = {
	//uiAudChannels,            uiAudioSR                      uiAudBits                  uiAudBufUnitTime
	IPCAM_AUD_OUT_MAX_CHANNELS, IPCAM_AUD_OUT_MAX_SAMPLE_RATE, IPCAM_AUD_OUT_MAX_BIT,     1,               0
};

static UIAPPIPCAM_VOUT_SETTING g_VideoOutInfo = {UIAPPIPCAM_VOUT_AUTO, TRUE};



UIAPPIPCAM_IME_SCALE_TYPE * UIAppIPCam_get_IMEScaleInfo(void){

	return &g_UIAppIPCamIMEScaleConfig[0];
}

WAVSTUD_INFO_SET * UIAppIPCam_get_AudioInMaxInfo(void){

	return &g_AudioInMaxInfo;
}

NMI_AUDENC_MAX_MEM_INFO * UIAppIPCam_get_AudioEncMaxInfo(void){

	return &g_AudioEncMaxInfo;
}

NMI_AUDDEC_MAX_MEM_INFO * UIAppIPCam_get_AudioDecMaxInfo(void)
{
	return &g_AudioDecMaxInfo;
}

WAVSTUD_INFO_SET * UIAppIPCam_get_AudioOutMaxInfo(void){

	return &g_AudioOutMaxInfo;
}

STMRCV_MAX_MEM_INFO * UIAppIPCam_get_StreamReceiverMaxInfo(void){

	return &g_StreamReceiverMaxInfo;
}

UIAPPIPCAM_EVBR_CONFIG *UIAppIPCam_get_EVBRInfo(void){

	return &g_UIAppIPCamEVBRConfig[0];
}

UIAPPIPCAM_VIDEO_MAXCONFIG *UIAppIPCam_get_VdoMaxConfig(void)
{

	return &g_UIAppIPCamVdoMaxBufConfig[0];

}

UIAPPIPCAM_IPL_FUNC *UIAppIPCam_get_IPLFuncInfo(void)
{

	return &g_UIAppIPCamIPLFuncConfig[0];

}

UIAPPIPCAM_AQ_CONFIG *UIAppIPCam_get_AQInfo(void)
{

	return &g_UIAppIPCamAQConFig[0];

}


UIAPPIPCAM_FIXQP_CONFIG *UIAppIPCam_get_FixQPInfo(void)
{

	return &g_UIAppIPCamFIXQPConFig[0];

}

UIAPPIPCAM_CROP_INFO *UIAppIPCam_get_CropInfo(void)
{

	return &g_UIAppIPCamCropInfo[0];

}

UIAPPIPCAM_CBR_CONFIG *UIAppIPCam_get_CBRInfo(void)
{

	return &g_UIAppIPCamCBRConFig[0];

}

UIAPPIPCAM_VBR_CONFIG *UIAppIPCam_get_VBRInfo(void)
{

	return &g_UIAppIPCamVBRConFig[0];

}

UIAPPIPCAM_BRC_NONE_CONFIG *UIAppIPCam_get_BRCNoneInfo(void)
{

	return &g_UIAppIPCamBRCNoneConFig[0];

}


void UIAppIPCam_set_IMEScaleInfo(UIAPPIPCAM_IME_SCALE_TYPE *pIMEInfo){

	DBG_FUNC_BEGIN("\r\n");

	if (pIMEInfo != NULL) {
		memcpy(&g_UIAppIPCamIMEScaleConfig, pIMEInfo, sizeof(UIAPPIPCAM_IME_SCALE_TYPE)*UIAPPIPCAM_SENSOR_MAX);
	} else {
		DBG_ERR("pIMEInfo is null\r\n");
	}

	DBG_FUNC_END("\r\n");

}

void UIAppIPCam_set_EVBRInfo(UIAPPIPCAM_EVBR_CONFIG *pEVBRInfo){

	DBG_FUNC_BEGIN("\r\n");

	if (pEVBRInfo != NULL) {
		memcpy(&g_UIAppIPCamEVBRConfig, pEVBRInfo, sizeof(UIAPPIPCAM_EVBR_CONFIG)*UIAPPIPCAM_PATH_MAX_ID);
	} else {
		DBG_ERR("g_UIAppIPCamEVBRConfig is null\r\n");
	}

	DBG_FUNC_END("\r\n");

}

void UIAppIPCam_set_IPLFuncInfo(UIAPPIPCAM_IPL_FUNC *pIPLFuncInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pIPLFuncInfo != NULL) {
		memcpy(&g_UIAppIPCamIPLFuncConfig, pIPLFuncInfo, sizeof(UIAPPIPCAM_IPL_FUNC)*UIAPPIPCAM_SENSOR_MAX);
	} else {
		DBG_ERR("pIPLFuncInfo is null\r\n");
	}

	DBG_FUNC_END("\r\n");
}

void UIAppIPCam_set_AQInfo(UIAPPIPCAM_AQ_CONFIG *pAQInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pAQInfo != NULL) {
		memcpy(&g_UIAppIPCamAQConFig, pAQInfo, sizeof(UIAPPIPCAM_AQ_CONFIG)*UIAPPIPCAM_PATH_MAX_ID);
	} else {
		DBG_ERR("pAQInfo is null\r\n");
	}

	DBG_FUNC_END("\r\n");
}

void UIAppIPCam_set_FixQPInfo(UIAPPIPCAM_FIXQP_CONFIG *pFixQPInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pFixQPInfo != NULL) {
		memcpy(&g_UIAppIPCamFIXQPConFig, pFixQPInfo, sizeof(UIAPPIPCAM_FIXQP_CONFIG)*UIAPPIPCAM_PATH_MAX_ID);
	} else {
		DBG_ERR("pFixQPInfo is null\r\n");
	}

	DBG_FUNC_END("\r\n");
}

void UIAppIPCam_set_CropInfo(UIAPPIPCAM_CROP_INFO *pCropInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pCropInfo != NULL) {
		memcpy(&g_UIAppIPCamCropInfo, pCropInfo, sizeof(UIAPPIPCAM_CROP_INFO)*UIAPPIPCAM_SENSOR_MAX);
	} else {
		DBG_ERR("pCropInfo is null\r\n");
	}


	DBG_FUNC_END("\r\n");
}

void UIAppIPCam_set_BRCNoneInfo(UIAPPIPCAM_BRC_NONE_CONFIG *pBRCNoneInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pBRCNoneInfo != NULL) {
		memcpy(&g_UIAppIPCamBRCNoneConFig, pBRCNoneInfo, sizeof(UIAPPIPCAM_BRC_NONE_CONFIG)*UIAPPIPCAM_PATH_MAX_ID);
	} else {
		DBG_ERR("pBRCNoneInfo is null\r\n");
	}


	DBG_FUNC_END("\r\n");
}


void UIAppIPCam_set_VBRInfo(UIAPPIPCAM_VBR_CONFIG *pVBRInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pVBRInfo != NULL) {
		memcpy(&g_UIAppIPCamVBRConFig, pVBRInfo, sizeof(UIAPPIPCAM_VBR_CONFIG)*UIAPPIPCAM_PATH_MAX_ID);
	} else {
		DBG_ERR("pVBRInfo is null\r\n");
	}


	DBG_FUNC_END("\r\n");
}

void UIAppIPCam_set_CBRInfo(UIAPPIPCAM_CBR_CONFIG *pCBRInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pCBRInfo != NULL) {
		memcpy(&g_UIAppIPCamCBRConFig, pCBRInfo, sizeof(UIAPPIPCAM_CBR_CONFIG)*UIAPPIPCAM_PATH_MAX_ID);
	} else {
		DBG_ERR("pCBRInfo is null\r\n");
	}


	DBG_FUNC_END("\r\n");
}


UIAPPIPCAM_VOUT_SETTING *UIAppIPCam_get_VoutInfo(void)
{

	return &g_VideoOutInfo;

}

void UIAppIPCam_set_VoutInfo(UIAPPIPCAM_VOUT_SETTING *pVoutInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pVoutInfo != NULL) {
		memcpy(&g_VideoOutInfo, pVoutInfo, sizeof(UIAPPIPCAM_VOUT_SETTING));
	} else {
		DBG_ERR("pVoutInfo is null\r\n");
	}


	DBG_FUNC_END("\r\n");
}


IPCAM_STREAM_INFO *UIAppIPCam_get_streamInfo(void)
{

	return &g_ImageAppStreamInfo[0];
}

UIAPPIPCAM_BLOCK_BUFFER_INFO *UIAppIPCam_get_BlockBufferInfo(void)
{
	return &g_UIAppIPCamBlockBufferInfo[0];
}

void UIAppIPCam_set_BlockBufferInfo(UIAPPIPCAM_BLOCK_BUFFER_INFO *pCombuf)
{

	DBG_FUNC_BEGIN("\r\n");
	if (pCombuf != NULL) {
		memcpy(g_UIAppIPCamBlockBufferInfo, pCombuf, sizeof(UIAPPIPCAM_BLOCK_BUFFER_INFO)*NVTMPP_VB_MAX_COMM_POOLS);

	} else {
		DBG_ERR("pCombuf is null\r\n");
	}
	DBG_FUNC_END("\r\n");

}

void UIAppIPCam_set_StreamInfo(IPCAM_STREAM_INFO *streamInfo)
{
	DBG_FUNC_BEGIN("\r\n");
	if (streamInfo != NULL) {
		memcpy(g_ImageAppStreamInfo, streamInfo, sizeof(IPCAM_STREAM_INFO)*UIAPPIPCAM_PATH_MAX_ID);

		ImageApp_IPCam_set_StreamInfo(&g_ImageAppStreamInfo[0]);

	} else {
		DBG_ERR("streamInfo is null\r\n");
	}
	DBG_FUNC_END("\r\n");

}


static UIAPPIPCAM_AUDIO_INFO    g_AudioInfo = { 0 };
UIAPPIPCAM_AUDIO_INFO *UIAppIPCam_get_AudioInfo(void)
{
	if (g_AudioInfo.SampleRate == 0) {
		g_AudioInfo.codec = AUDENC_ENCODER_PCM;
		if (IPCAM_AUD_IN_MAX_CHANNELS == 1)
			g_AudioInfo.channel = AUDIO_CH_LEFT;
		else
			g_AudioInfo.channel = AUDIO_CH_STEREO;
		g_AudioInfo.SampleRate = IPCAM_AUD_IN_MAX_SAMPLE_RATE;
		g_AudioInfo.volume = 100;
		g_AudioInfo.G711Sample = 1024;
	}
	return &g_AudioInfo;

}

void UIAppIPCam_set_AudioInfo(UIAPPIPCAM_AUDIO_INFO *pAudioInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pAudioInfo != NULL) {
		memcpy(&g_AudioInfo, pAudioInfo, sizeof(UIAPPIPCAM_AUDIO_INFO));
	} else {
		DBG_ERR("pAudioInfo is null\r\n");
	}


	DBG_FUNC_END("\r\n");
}

static UIAPPIPCAM_AUDIO_INFO    g_AudioOutInfo = { 0 };
UIAPPIPCAM_AUDIO_INFO *UIAppIPCam_get_AudioOutInfo(void)
{
	if (g_AudioOutInfo.SampleRate == 0) {
		g_AudioOutInfo.codec = AUDENC_ENCODER_PCM;
		if (IPCAM_AUD_OUT_MAX_CHANNELS == 1)
			g_AudioOutInfo.channel = AUDIO_CH_LEFT;
		else
			g_AudioOutInfo.channel = AUDIO_CH_STEREO;
		g_AudioOutInfo.SampleRate = IPCAM_AUD_OUT_MAX_SAMPLE_RATE;
		g_AudioOutInfo.volume = 100;
	}
	return &g_AudioOutInfo;

}

void UIAppIPCam_set_AudioOutInfo(UIAPPIPCAM_AUDIO_INFO *pAudioOutInfo)
{
	DBG_FUNC_BEGIN("\r\n");

	if (pAudioOutInfo != NULL) {
		memcpy(&g_AudioOutInfo, pAudioOutInfo, sizeof(UIAPPIPCAM_AUDIO_INFO));
	} else {
		DBG_ERR("pAudioOutInfo is null\r\n");
	}


	DBG_FUNC_END("\r\n");
}


void UIAppIPCam_set_SensorInfo(UIAPPIPCAM_SENSOR_INFO *SensorInfo)
{
	DBG_FUNC_BEGIN("\r\n");
	if (SensorInfo != NULL) {
		memcpy(g_UIAppIPCamSensorInfo, SensorInfo, sizeof(UIAPPIPCAM_SENSOR_INFO)*UIAPPIPCAM_SENSOR_MAX);
	} else {
		DBG_ERR("sensorInfo is null\r\n");
	}
	DBG_FUNC_END("\r\n");
}
UIAPPIPCAM_SENSOR_INFO *UIAppIPCam_get_SensorInfo(void)
{

	return &g_UIAppIPCamSensorInfo[0];
}

UIAPPIPCAM_ENCODE_CONFIG *UIAppIPCam_get_EncodeConfig(void)
{

	return &g_UIAppIPCamEncodeConfig[0];

}

void UIAppIPCam_set_EncodeConfig(UIAPPIPCAM_ENCODE_CONFIG *EncodeConfig)
{
	DBG_FUNC_BEGIN("\r\n");
	if (EncodeConfig != NULL) {
		memcpy(g_UIAppIPCamEncodeConfig, EncodeConfig, sizeof(UIAPPIPCAM_ENCODE_CONFIG)*UIAPPIPCAM_PATH_MAX_ID);
	} else {
		DBG_ERR("EncodeConfig is null\r\n");
	}
	DBG_FUNC_END("\r\n");
}

void UIAppIPCam_set_YUVPath(INT32 path)
{
	////if path == -1 , means close yuv path
	if (path < -1 || path >= UIAPPIPCAM_PATH_MAX_ID) {
		DBG_ERR("set YUV path error, path =%d\r\n", path);
		return;
	}
	g_iYUVPath = path;
	ImageApp_IPCam_Config(IPCAM_YUV_PATH, g_iYUVPath);


}


INT32 UIAppIPCam_get_YUVPath(void)
{

	return g_iYUVPath;

}

void UIAppIPCam_set_DisplayPath(INT32 path)
{
	////if path == -1 , means close display path
	if (path < -1 || path >= UIAPPIPCAM_PATH_MAX_ID) {
		DBG_ERR("set display path error, path =%d\r\n", path);
		return;
	}

	//path = IPCAM_DISP_PATH_NO;
	g_iDisplayPath = path;
	ImageApp_IPCam_Config(IPCAM_DISP_PATH, g_iDisplayPath);


}


INT32 UIAppIPCam_get_DisplayPath(void)
{


	return g_iDisplayPath;

}

INT32 UIAppIPCam_get_ALGPath(void)
{


	return g_iALGPath;

}

void UIAppIPCam_set_ALGPath(INT32 path)
{
	////if path == -1 , means close ALG path
	if (path < -1 || path >= UIAPPIPCAM_PATH_MAX_ID) {
		DBG_ERR("set display path error, path =%d\r\n", path);
		return;
	}

	g_iALGPath = path;
	ImageApp_IPCam_Config(IPCAM_ALG_PATH, g_iALGPath);

}

ISF_PORT_STATE UIAppIPCam_Get_Unit_Status(UIAPPIPCAM_UNIT unit){

	switch(unit){

		case UIAPPIPCAM_VDOOUT_UNIT:
			return ImageApp_IPCam_GetConfig(IPCAM_DISP_STATUS);
		default:
			DBG_ERR("error unit %d\r\n",unit);
			break;
	}
	return UIAPPIPCAM_MAX_UNIT;
}

void UIAppIPCam_Set_Unit_Status(UIAPPIPCAM_UNIT unit, ISF_PORT_STATE status){

	switch(unit){

		case UIAPPIPCAM_VDOOUT_UNIT:
			ImageApp_IPCam_Config(IPCAM_DISP_STATUS,status);
			break;
		default:
			DBG_ERR("error unit %d\r\n",unit);
			break;

	}

}


