/*
    Copyright   Novatek Microelectronics Corp. 2005~2017.  All rights reserved.

    @file       ImageUnit_AudEnc.h
    @ingroup    mVdoIn

    @note       Nothing.

    @date       2017/04/12
*/

#ifndef IMAGEUNIT_AUDENC_H
#define IMAGEUNIT_AUDENC_H

#include "ImageStream.h"
#include "NMediaRecAPI.h"

typedef enum {
	AUDENC_PARAM_START                  = 0x0000F000,
	AUDENC_PARAM_CODEC                  = AUDENC_PARAM_START,
	AUDENC_PARAM_ENCODER_OBJ,
	AUDENC_PARAM_CHS,
	AUDENC_PARAM_SAMPLERATE,
	AUDENC_PARAM_AAC_ADTS_HEADER,
	AUDENC_PARAM_FILETYPE,
	AUDENC_PARAM_RECFORMAT,
	AUDENC_PARAM_MAX_MEM_INFO,
	AUDENC_PARAM_FIXED_SAMPLE,
	AUDENC_PARAM_MAX_FRAME_QUEUE,
	AUDENC_PARAM_ENCBUF_MS,
	AUDENC_PARAM_SKIP_PCM_COPY,                                     ///< switch SKIP_PCM_COPY flow
	AUDENC_PARAM_MUTE_ENC_FUNC_EN,
	AUDENC_PARAM_MUTE_ENC_IMM,
	AUDENC_PARAM_TARGETRATE,                                        ///< only valid for AAC
	AUDENC_PARAM_MAX,
	ENUM_DUMMY4WORD(AUDENC_PARAM)
} AUDENC_PARAM;

typedef enum {
	AUDENC_PARAM_PORT_START             = 0x0000FF00,
	AUDENC_PARAM_PORT_OUTPUT_FMT        = AUDENC_PARAM_PORT_START,
	AUDENC_PARAM_PORT_MAX,
	ENUM_DUMMY4WORD(AUDENC_PARAM_PORT)
} AUDENC_PARAM_PORT;

typedef enum {
	AUDENC_ENCODER_NONE                 = 0,
	AUDENC_ENCODER_PCM                  = NMEDIAREC_ENC_PCM,
	AUDENC_ENCODER_AAC                  = NMEDIAREC_ENC_AAC,
	AUDENC_ENCODER_PPCM                 = NMEDIAREC_ENC_PPCM,
	AUDENC_ENCODER_ULAW                 = NMEDIAREC_ENC_ULAW,
	AUDENC_ENCODER_ALAW                 = NMEDIAREC_ENC_ALAW,
	ENUM_DUMMY4WORD(AUDENC_ENCODER)
} AUDENC_ENCODER;

typedef enum {
	AUDENC_OUTPUT_NONE                  = 0,
	AUDENC_OUTPUT_UNCOMPRESSION,
	AUDENC_OUTPUT_COMPRESSION,
	ENUM_DUMMY4WORD(AUDENC_OUTPUT)
} AUDENC_OUTPUT;

typedef enum {
	AUDENC_BITRATE_16000                = 16000,
	AUDENC_BITRATE_32000                = 32000,
	AUDENC_BITRATE_48000                = 48000,
	AUDENC_BITRATE_64000                = 64000,
	AUDENC_BITRATE_80000                = 80000,
	AUDENC_BITRATE_96000                = 96000,
	AUDENC_BITRATE_112000               = 112000,
	AUDENC_BITRATE_128000               = 128000,
	AUDENC_BITRATE_144000               = 144000,
	AUDENC_BITRATE_160000               = 160000,
	AUDENC_BITRATE_192000               = 192000,
	ENUM_DUMMY4WORD(AUDENC_BITRATE)
} AUDENC_BITRATE;

extern ISF_UNIT ISF_AudEnc;

extern void ISF_AudEnc_InstallID(void) _SECTION(".kercfg_text");
extern UINT32 _SECTION(".kercfg_data") ISF_AUDENC_SEM_ID[];
extern UINT32 _SECTION(".kercfg_data") ISF_AUDENC_COMMON_SEM_ID;

#endif //IMAGEUNIT_AUDENC_H

