#define CONFIG_MODEL_NVT_FPGA

/* NVT board configuration */
#define CONFIG_MEM_BASE				_BOARD_DRAM_ADDR_
#define CONFIG_MEM_SIZE				_BOARD_DRAM_SIZE_
/* 6MB for kernel image */
#define CONFIG_BOARD_REV_ADDR           _BOARD_REV_ADDR_
#define CONFIG_BOARD_REV_SIZE           _BOARD_REV_SIZE_
#define CONFIG_NVT_UIMAGE_SIZE			(SZ_1M * 4)
#define CONFIG_NVT_UIMAGE_UNZIP_SIZE	(SZ_1M * 8)
#define CONFIG_NVT_ITRON_UNZIP_SIZE	    (SZ_1M * 10)

#define CONFIG_DSP_SDRAM_BASE			_BOARD_DSP1_ADDR_
#define CONFIG_DSP_SDRAM_SIZE			_BOARD_DSP1_SIZE_
#define CONFIG_DSP_BOOT_TMP_BUF_ADDR		_BOARD_UITRON_ADDR_
#define CONFIG_DSP_BOOT_TMP_BUF_SIZE		(SZ_1M * 10)		// Avoid exceed CONFIG_NVT_RUNFW_SDRAM_BASE
#define CONFIG_RAMDISK_SDRAM_BASE		_BOARD_RAMDISK_ADDR_
#define CONFIG_RAMDISK_SDRAM_SIZE		_BOARD_RAMDISK_SIZE_
#define CONFIG_ITRON_SDRAM_BASE			_BOARD_UITRON_ADDR_
#define CONFIG_ITRON_SDRAM_SIZE			_BOARD_UITRON_SIZE_

#define CONFIG_UBOOT_SDRAM_BASE			_BOARD_UBOOT_ADDR_
#define CONFIG_UBOOT_SDRAM_SIZE			_BOARD_UBOOT_SIZE_
#define CONFIG_LINUX_SDRAM_BASE			_BOARD_LINUX_ADDR_
#define CONFIG_LINUX_SDRAM_SIZE			_BOARD_LINUX_SIZE_
/* temp buffer for all-in-one T.bin boot requirement */
#if (_BOARD_LINUX_SIZE_ >= ((SZ_1M * 20) + CONFIG_NVT_UIMAGE_SIZE))
#define CONFIG_NVT_RUNFW_SDRAM_BASE     (CONFIG_ITRON_SDRAM_BASE + CONFIG_NVT_ITRON_UNZIP_SIZE) //compressed uitron image address
#define CONFIG_NVT_RUNFW_SDRAM_SIZE     (CONFIG_ITRON_SDRAM_SIZE - CONFIG_NVT_ITRON_UNZIP_SIZE)
#else
#define CONFIG_NVT_RUNFW_SDRAM_BASE		(CONFIG_ITRON_SDRAM_BASE + (SZ_1M * 40))
#define CONFIG_NVT_RUNFW_SDRAM_SIZE     (CONFIG_MEM_SIZE - CONFIG_NVT_RUNFW_SDRAM_BASE)
#endif
#define CONFIG_LINUX_SDRAM_START		(CONFIG_UBOOT_SDRAM_BASE - CONFIG_NVT_UIMAGE_SIZE)
#define CONFIG_LINUX_UNZIP_SDRAM_END	(CONFIG_LINUX_SDRAM_BASE + CONFIG_NVT_UIMAGE_UNZIP_SIZE)
#define CONFIG_LINUX_SDRAM_MEMRESERVED_BASE	(_BOARD_DRAM_SIZE_ - CONFIG_DSP_SDRAM_SIZE - _BOARD_RAMDISK_SIZE_ - _BOARD_UITRON_RESV_SIZE_)
#define CONFIG_LINUX_SDRAM_MEMRESERVED_SIZE	_BOARD_UITRON_RESV_SIZE_

#define CONFIG_SMEM_SDRAM_BASE			_BOARD_IPC_ADDR_
#define CONFIG_MODELEXT_SDRAM_BASE		CONFIG_SMEM_SDRAM_BASE
#define CONFIG_MODELEXT_SDRAM_SIZE		0x1000
#define CONFIG_NVTIPC_SHARED_MEM_ADDR		0x00100000	///< the ipc shared memory is in DRAM 1MB.
#define CONFIG_NVTIPC_SHARED_MEM_SIZE		0x1000
#define CONFIG_SMEM_SDRAM_SIZE			_BOARD_IPC_SIZE_

#define CONFIG_MODELEXT_SPINAND_BASE		0x40000
#define CONFIG_MODELEXT_SPINOR_BASE             0x10000
#define CONFIG_MODELEXT_EMMC_BASE		0x200

#define CONFIG_SYS_NAND_BASE			0xC0400000
#define CONFIG_SYS_HZ_CLOCK			24000000
