//This source code is generated by UI Designer Studio.

#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "UIGraphics.h"
#include "NVTToolCommand.h"
#include "UIFlowWndPlayRes.c"
#include "UIFlowWndPlay.h"
#include "UIFlowWndPlayMagnify.h"
#include "AppCommon.h"
#include "Audio.h"
#include "UICommon.h"
#include "UIFlow.h"
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
#include "SMediaPlayAPI.h"
#include "DCF.h"
#include "UIAppMoviePlay.h"
//#NT#2012/08/31#Calvin Chang -end
#include "UIAppPlay.h"

#include "UIPlayComm.h"
// Photo mode key mask
#include "FileDB.h"
#include "GxVideoFile.h"
#include "ImageApp_Play.h"

#include "ImageApp_MoviePlay.h"
#include "AppDisp_MoviePlayView.h"

#define PLAY_KEY_PRESS_MASK        (FLGKEY_KEY_MASK_DEFAULT)
#define PLAY_KEY_RELEASE_MASK      FLGKEY_MODE//(FLGKEY_UP | FLGKEY_DOWN | FLGKEY_LEFT | FLGKEY_RIGHT)
#define PLAY_KEY_CONTINUE_MASK     FLGKEY_KEY_CONT_MASK_DEFAULT

#define FULL_FILE_PATH_LEN      64

BOOL           g_bUIFlowWndPlayNoImgWndOpened   = FALSE;
UINT32         g_uiUIFlowWndPlayCurrentVolume   = AUDIO_VOL_5;
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
UINT32         g_uiUIFlowWndPlayCurrenSpeed     = SMEDIAPLAY_SPEED_NORMAL;
UINT32         g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;
SMEDIAPLAY_USEROBJ  g_UIPlayMediaObj                 = {0};
MOVIEPLAY_FILEPLAY_INFO gMovie_Play_Info        = {0};

FST_FILE       gphUIFlowMovPlay_Filehdl         = NULL;
//#NT#2012/08/31#Calvin Chang -end

MOVIEPLAY_DISP_INFO  gUIFlowWndPlayDispConfig[4] = {
    //enable  disp_id       w     h      ratio     rotate dir
	{TRUE, MOVIEPLAY_DISP_ID_1, 960,  240  ,  4 ,  3  ,  0},
	{TRUE, MOVIEPLAY_DISP_ID_2, 960,  240  ,  4 ,  3  ,  0},
	{TRUE, MOVIEPLAY_DISP_ID_3, 960,  240  ,  4 ,  3  ,  0},
	{TRUE, MOVIEPLAY_DISP_ID_4, 960,  240  ,  4 ,  3  ,  0},
};

//---------------------UIFlowWndPlayCtrl Function ---------------------------
//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel);
//#NT#2012/08/31#Calvin Chang -end
void UIFlowWndPlay_ConfigDispInfo(void);
//---------------------UIFlowWndPlayCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIFlowWndPlay)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_DSCMode)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Flash)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_EV)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Size)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_WB)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Quality)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Sharpness)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Storage)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Battery)
CTRL_LIST_ITEM(UIFlowWndPlay_TabHistogram)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Filename)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_Protect)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Date)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Time)
CTRL_LIST_ITEM(UIFlowWndPlay_Histo)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_MovPlay)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_MovStop)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_MovBwd)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_MovPlayTime)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_MovFwd)
CTRL_LIST_ITEM(UIFlowWndPlay_StatusICN_Volumn)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticICN_Print)
CTRL_LIST_ITEM(UIFlowWndPlay_StaticTXT_Speed)
CTRL_LIST_END

//----------------------UIFlowWndPlayCtrl Event---------------------------
INT32 UIFlowWndPlay_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyUp(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDown(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyLeft(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyRight(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMode(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnChildClose(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBattery(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyEnter(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieFinish(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIFlowWndPlay_OnKeyMenu(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay)
EVENT_ITEM(NVTEVT_OPEN_WINDOW,UIFlowWndPlay_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW,UIFlowWndPlay_OnClose)
EVENT_ITEM(NVTEVT_KEY_UP,UIFlowWndPlay_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_DOWN,UIFlowWndPlay_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_LEFT,UIFlowWndPlay_OnKeyLeft)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndPlay_OnKeyRight)
EVENT_ITEM(NVTEVT_KEY_ZOOMIN,UIFlowWndPlay_OnKeyZoomin)
EVENT_ITEM(NVTEVT_KEY_ZOOMOUT,UIFlowWndPlay_OnKeyZoomout)
EVENT_ITEM(NVTEVT_KEY_ENTER,UIFlowWndPlay_OnKeyEnter)
EVENT_ITEM(NVTEVT_KEY_DISPLAY,UIFlowWndPlay_OnKeyDisplay)
EVENT_ITEM(NVTEVT_KEY_MODE,UIFlowWndPlay_OnKeyMode)
EVENT_ITEM(NVTEVT_CHILD_CLOSE,UIFlowWndPlay_OnChildClose)
EVENT_ITEM(NVTEVT_BATTERY,UIFlowWndPlay_OnBattery)
EVENT_ITEM(NVTEVT_BATTERY_LOW,UIFlowWndPlay_OnBatteryLow)
EVENT_ITEM(NVTEVT_KEY_SHUTTER2,UIFlowWndPlay_OnKeyShutter2)
EVENT_ITEM(NVTEVT_KEY_PLAYBACK,UIFlowWndPlay_OnKeyPlayback)
EVENT_ITEM(NVTEVT_CB_MOVIE_FINISH,UIFlowWndPlay_OnMovieFinish)
EVENT_ITEM(NVTEVT_CB_MOVIE_ONE_SEC,UIFlowWndPlay_OnMovieOneSec)
EVENT_ITEM(NVTEVT_STORAGE_INIT,UIFlowWndPlay_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE,UIFlowWndPlay_OnStorageChange)
EVENT_ITEM(NVTEVT_KEY_MENU,UIFlowWndPlay_OnKeyMenu)
EVENT_END

static void UIFlowWndPlay_CheckStatus(void)
{
    UINT32 uiStatus, uiCurrMode;
    uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
    PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);

    // Decode Error & Read Error
    if( uiStatus & (PB_STA_ERR_FILE | PB_STA_ERR_DECODE) )
    {
        if(uiCurrMode == PLAYMODE_AVI || uiCurrMode == PLAYMODE_MOVMJPG)
        {
            UINT32  uiBuffAddr, uiBuffSize;
            CHAR    chaFullName[64] = { 0 };

            PB_GetParam(PBPRMID_DATABUF_ADDR, &uiBuffAddr);
            PB_GetParam(PBPRMID_DATABUF_SIZE, &uiBuffSize);
            PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)&chaFullName);
            SMediaPlay_FileRecovery(chaFullName, uiBuffAddr, uiBuffSize);
            FileDB_Refresh(0);//2016/04/11
            uiStatus = UIPlay_PlaySingle(PB_SINGLE_CURR);
            if( uiStatus == PB_STA_DONE)
                return;
        }
		Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, FLOWWRNMSG_ISSUE_PICTURE_ERR, FLOWWRNMSG_TIMER_2SEC);
    }
}

#if 1
static INT32 UIFlowWndPlay_OnExeUpKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiCurrMode;
    PB_GetParam(PBPRMID_PLAYBACK_MODE, &uiCurrMode);
    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            if (uiCurrMode == PLAYMODE_PRIMARY && PB_WaitCommandFinish(PB_WAIT_INFINITE) == PB_STA_DONE)
            {
                Ux_OpenWindow((VControl *)(&UIFlowWndPlayMagnifyCtrl), 0);
            }
            break;
        case PLB_ST_PLAY_MOV:
                if (g_uiUIFlowWndPlayCurrentVolume < AUDIO_VOL_7)
                {
                    // Start to Play
                    g_uiUIFlowWndPlayCurrentVolume++;
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,NVTEVT_EXE_MOVIEAUDPLAYVOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                    //Ux_SendEvent(&CustomMoviePlayObjCtrl,
                    //             NVTEVT_EXE_STARTPLAY,
                    //             2,
                    //             g_uiUIFlowWndPlayCurrenSpeed,
                    //             g_uiUIFlowWndPlayCurrenDirection);
                    FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
                }
            break;

    }
    return NVTEVT_CONSUME;
}

static INT32 UIFlowWndPlay_OnExeDownKeyAct(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32 uiActKey;

    if (paramNum >= 1)
        uiActKey = paramArray[0];
    else {
        debug_msg("error parameter!!\r\n");
        return NVTEVT_CONSUME;
    }

    switch (uiActKey)
    {
      case NVTEVT_KEY_PRESS:
           switch(g_PlbData.State)
            {
                case PLB_ST_FULL:
                    Ux_OpenWindow((VControl *)(&UIFlowWndPlayThumbCtrl), 0);
                    break;
                case PLB_ST_PLAY_MOV:
                        if (g_uiUIFlowWndPlayCurrentVolume > AUDIO_VOL_MUTE)
                        {
                            // Start to Play
                            g_uiUIFlowWndPlayCurrentVolume--;
                            Ux_SendEvent(&CustomMoviePlayObjCtrl,NVTEVT_EXE_MOVIEAUDPLAYVOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                            //Ux_SendEvent(&CustomMoviePlayObjCtrl,
                            //             NVTEVT_EXE_STARTPLAY,
                            //             2,
                            //             g_uiUIFlowWndPlayCurrenSpeed,
                            //             g_uiUIFlowWndPlayCurrenDirection);
                            FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
                        }
                    break;
            }
        break;
    }
    return NVTEVT_CONSUME;
}
#endif

INT32 UIFlowWndPlay_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiSoundMask,uiStatus;
    UINT32 uiFileNum = 0;

    g_bUIFlowWndPlayNoImgWndOpened = FALSE;

	// check whether card removed or not
    if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED || (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE))
    {
		if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
			if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED) {
				Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_2SEC);
			} else {
				Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORYERROR, FLOWWRNMSG_TIMER_KEEP);
			}
		}
		// enable shutter2 sound
		uiSoundMask = Input_GetKeySoundMask(KEY_PRESS);
		uiSoundMask |= FLGKEY_SHUTTER2;
		Input_SetKeySoundMask(KEY_PRESS, uiSoundMask);

		// Set mask key
		Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
		Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
		Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
		Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);

		Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
        return NVTEVT_CONSUME;
    }
    PB_WaitCommandFinish(PB_WAIT_INFINITE);
    //After playback ready, point to the last file
    PB_GetParam(PBPRMID_TOTAL_FILE_COUNT, &uiFileNum);
//    PB_OpenSpecFileBySeq(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT), TRUE);
    PB_OpenSpecFileBySeq(uiFileNum, TRUE);
    UIPlay_PlaySingle(PB_SINGLE_CURR);
    uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);

    //disable video2 and enable video 1
    Display_ShowPreview();

    UpdateVdoWinForPB();

    if (uiStatus & PB_STA_NOIMAGE)
    //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
    {
        Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_IMAGE,FLOWWRNMSG_TIMER_KEEP);
        g_bUIFlowWndPlayNoImgWndOpened = TRUE;
    }
    else
    {
        g_PlbData.VideoPBSpeed=PLB_FWD_MOV_1x;
        g_PlbData.State = PLB_ST_FULL;
        UIFlowWndPlay_CheckStatus();
        FlowPB_UpdateIcons(1);
    }

    // enable shutter2 sound
    uiSoundMask = Input_GetKeySoundMask(KEY_PRESS);
    uiSoundMask |= FLGKEY_SHUTTER2;
    Input_SetKeySoundMask(KEY_PRESS, uiSoundMask);

    // Set mask key
    Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
    Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
    Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
    Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);

    Ux_DefaultEvent(pCtrl,NVTEVT_OPEN_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32  uiSoundMask;

    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            break;

        case PLB_ST_PLAY_MOV:
        case PLB_ST_PAUSE_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            g_PlbData.State        = PLB_ST_FULL;
            g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
            UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
            g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

			ImageApp_MoviePlay_Close();
        	if (gMovie_Play_Info.event_cb) {
				#if (NMEDIAPLAY_FUNC == DISABLE)
				gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
				#else //((NMEDIAPLAY_FUNC == ENABLE))
				gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
				#endif
			}

            if (gphUIFlowMovPlay_Filehdl)
            {
                FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                gphUIFlowMovPlay_Filehdl = NULL;
            }
            break;
    }

    // disable shutter2 sound
    uiSoundMask = Input_GetKeySoundMask(KEY_PRESS);
    uiSoundMask &= ~FLGKEY_SHUTTER2;
    Input_SetKeySoundMask(KEY_PRESS, uiSoundMask);

    //#NT#2012/10/23#Philex Lin - begin
    // enable auto power off/USB detect timer
    // enable sound key tone
    KeyScan_EnableMisc(TRUE);
    //#NT#2012/10/23#Philex Lin - end
    //g_PlbData.VideoPBSpeed=PLB_FWD_MOV_1x;
    Ux_DefaultEvent(pCtrl,NVTEVT_CLOSE_WINDOW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyUp(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 1
    return UIFlowWndPlay_OnExeUpKeyAct(pCtrl, paramNum, paramArray);
#else
    // the same behavior as LEFT key!
    return UIFlowWndPlay_OnKeyLeft(pCtrl, paramNum, paramArray);
#endif
}
INT32 UIFlowWndPlay_OnKeyDown(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if 1
    return UIFlowWndPlay_OnExeDownKeyAct(pCtrl, paramNum, paramArray);
#else
    // the same behavior as RIGHT key!
    return UIFlowWndPlay_OnKeyRight(pCtrl, paramNum, paramArray);
#endif
}
INT32 UIFlowWndPlay_OnKeyLeft(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
            UIPlay_PlaySingle(PB_SINGLE_PREV);
            FlowPB_UpdateIcons(1);
            UIFlowWndPlay_CheckStatus();
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            break;
        case PLB_ST_PLAY_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            //#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
           /* if(g_PlbData.VideoPBSpeed > PLB_BWD_MOV_8x)
            {
                g_PlbData.VideoPBSpeed --;

                Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);


                if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
                {
                    g_PlbData.State = PLB_ST_FWD_MOV;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

                    // Play
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,
                                 NVTEVT_EXE_STARTPLAY,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);
                }
                else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
                {
                    g_PlbData.State = PLB_ST_BWD_MOV;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;

                    // Play
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,
                                 NVTEVT_EXE_STARTPLAY,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);

                }
                else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
                {
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

                    // Play
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,
                                 NVTEVT_EXE_STARTPLAY,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);
                }

                FlowPB_IconDrawMovSpeed();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            }*/
            break;
            //#NT#2012/08/31#Calvin Chang -end
        case PLB_ST_PAUSE_MOV:
			#if 0
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
            Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_BWDSTEPPLAY, 0);
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
			#endif
            UIFlowWndPlay_OnMovieFinish(pCtrl, paramNum, paramArray);
	    	Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
            UIPlay_PlaySingle(PB_SINGLE_PREV);
            FlowPB_UpdateIcons(1);
            //UxState_SetData(&UIFlowWndPlay_StatusICN_MovPlayCtrl,STATE_CURITEM,UIFlowWndPlay_StatusICN_MovPlay_ICON_OK_PLAY);

            UIFlowWndPlay_CheckStatus();
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            break;

#if 0
        if (KeyScan_IsHDMIPlugIn()==FALSE) {
            if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_8x)
            {
                g_PlbData.VideoPBSpeed ++;

                Ux_FlushEvent();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

                if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVFWD,1,g_PlbData.VideoPBSpeed);
                    g_PlbData.State = PLB_ST_FWD_MOV;
                    // set mute in FWD playing
                    hdmitx_setAudMute(TRUE);
                }
                else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVBWD,1,g_PlbData.VideoPBSpeed);
                    g_PlbData.State = PLB_ST_BWD_MOV;
                    // set mute in BWD playing
                    hdmitx_setAudMute(TRUE);
                }
                else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVFWDSTOP,0);
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    /* Since Media FWD/BWD will set volume mute, we should restore current volume. */
                    hdmitx_setAudMute(FALSE);
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_AUD_VOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                }

                FlowPB_IconDrawMovSpeed();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            }
        }
#endif
        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
            UIPlay_PlaySingle(PB_SINGLE_NEXT);
            FlowPB_UpdateIcons(1);
            UIFlowWndPlay_CheckStatus();
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            break;
        case PLB_ST_PLAY_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            //#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
          /*  if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_8x)
            {
                g_PlbData.VideoPBSpeed ++;

                Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);

                if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
                {
                    g_PlbData.State = PLB_ST_FWD_MOV;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

                    // Play
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,
                                 NVTEVT_EXE_STARTPLAY,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);
                }
                else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
                {
                    g_PlbData.State = PLB_ST_BWD_MOV;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_BACKWARD;

                    // Play
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,
                                 NVTEVT_EXE_STARTPLAY,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);

                }
                else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
                {
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
                    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

                    // Play
                    Ux_SendEvent(&CustomMoviePlayObjCtrl,
                                 NVTEVT_EXE_STARTPLAY,
                                 2,
                                 g_uiUIFlowWndPlayCurrenSpeed,
                                 g_uiUIFlowWndPlayCurrenDirection);
                }
                FlowPB_IconDrawMovSpeed();
                Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            }*/
            break;
            //#NT#2012/08/31#Calvin Chang -end
        case PLB_ST_PAUSE_MOV:
			#if 0
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
            Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_FWDSTEPPLAY, 0);
            Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
			#endif
			UIFlowWndPlay_OnMovieFinish(pCtrl, paramNum, paramArray);
			Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
			UIPlay_PlaySingle(PB_SINGLE_NEXT);
			FlowPB_UpdateIcons(1);
			//UxState_SetData(&UIFlowWndPlay_StatusICN_MovPlayCtrl,STATE_CURITEM,UIFlowWndPlay_StatusICN_MovPlay_ICON_OK_PLAY);

			UIFlowWndPlay_CheckStatus();
			Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            break;

//#NT#2012/7/6#Philex mark temp
#if 0
        if (KeyScan_IsHDMIPlugIn()==FALSE) {
            if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_8x)
            {
                g_PlbData.VideoPBSpeed ++;

                Ux_FlushEvent();
                KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_NULL);

                if(g_PlbData.VideoPBSpeed > PLB_FWD_MOV_1x)
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVFWD,1,g_PlbData.VideoPBSpeed);
                    g_PlbData.State = PLB_ST_FWD_MOV;
                    // set mute in FWD playing
                    hdmitx_setAudMute(TRUE);
                }
                else if(g_PlbData.VideoPBSpeed < PLB_FWD_MOV_1x)
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVBWD,1,g_PlbData.VideoPBSpeed);
                    g_PlbData.State = PLB_ST_BWD_MOV;
                    // set mute in BWD playing
                    hdmitx_setAudMute(TRUE);
                }
                else   //uiCurrSpeedIndex == PLAYMOV_SPEED_FWD_1X
                {
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_MOVFWDSTOP,0);
                    g_PlbData.State = PLB_ST_PLAY_MOV;
                    /* Since Media FWD/BWD will set volume mute, we should restore current volume. */
                    hdmitx_setAudMute(FALSE);
                    Ux_SendEvent(&UIPlayObjCtrl,NVTEVT_AUD_VOLUME,1,g_uiUIFlowWndPlayCurrentVolume);
                }

                FlowPB_IconDrawMovSpeed();
                KeyScan_SetKeyMask(KEYSCAN_KEYMODE_PRESS, FLGKEY_KEY_MASK_DEFAULT);
            }
        }
        break;
#endif

    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomin(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyZoomout(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
    case PLB_ST_FULL:
        g_PlbData.State = PLB_ST_MENU;
        Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
        // Reset specific menu items
        SysSetFlag(FL_PROTECT, PROTECT_ONE);
        // Set Tab menu to Playback menu
        TM_SetMenu(&gPlaybackMenu);
        // Open common item menu
        Ux_OpenWindow(&MenuCommonItemCtrl, 0);
        break;
    case PLB_ST_PLAY_MOV:
    case PLB_ST_PAUSE_MOV:
        //#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
        g_PlbData.State        = PLB_ST_FULL;
        g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
        UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
        g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

        Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
        Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_CLOSEPLAY, 0);

        //#NT#2012/10/23#Philex Lin - begin
        // enable auto power off/USB detect timer
        // enable key tone flag
        KeyScan_EnableMisc(TRUE);
        //#NT#2012/10/23#Philex Lin - end

        // stop scan
        //if (SxTimer_GetFuncActive(SX_TIMER_DET_STRG_ID)==0)
    //        SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, TRUE);

        if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID)==0)
            SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);


        if (gphUIFlowMovPlay_Filehdl)
        {
            FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
            gphUIFlowMovPlay_Filehdl = NULL;
        }

        // Play 1st video frame image
        UIPlay_PlaySingle(PB_SINGLE_CURR);
        //#NT#2012/08/31#Calvin Chang -end

        FlowPB_UpdateIcons(1);


        break;
    }
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyDisplay(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyMode(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //if (KeyScan_IsHDMIPlugIn()==TRUE)
    //    return NVTEVT_CONSUME;

    switch(g_PlbData.State)
    {
    case PLB_ST_PLAY_MOV:
    case PLB_ST_PAUSE_MOV:
    case PLB_ST_FWD_MOV:
    case PLB_ST_BWD_MOV:
        // stop movie play
        return UIFlowWndPlay_OnMovieFinish(pCtrl, paramNum, paramArray);

    default:
        Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
        Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_NULL);
        Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
        Input_SetKeyMask(KEY_CONTINUE, FLGKEY_KEY_MASK_NULL);
        Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
        break;
    }

    return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnKeyMenu(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    UINT32 uiActKey;
    UINT32  uiSoundMask;
   CHKPNT;
    if (paramNum >= 1)
    	uiActKey = paramArray[0];
    else 
    {
    	debug_msg("error parameter!!\r\n");
    	return NVTEVT_CONSUME;
    }

    switch (uiActKey)
    {
	case NVTEVT_KEY_PRESS:
        switch(g_PlbData.State)
	{
    	    // enable shutter2 sound (shutter2 as OK key in menu)
            uiSoundMask = Input_GetKeySoundMask(KEY_PRESS);
            uiSoundMask |= FLGKEY_SHUTTER2;
            Input_SetKeySoundMask(KEY_PRESS, uiSoundMask);
            Input_SetKeyMask(KEY_RELEASE, FLGKEY_KEY_MASK_NULL);
        
	case PLB_ST_FULL:
		SysSetFlag(FL_PROTECT, PROTECT_ONE);
		// Set Tab menu to Playback menu
		TM_SetMenu(&gPlaybackMenu);
		// Open common item menu
		Ux_OpenWindow(&MenuCommonItemCtrl, 0);
		g_bUIFlowWndPlayNoImgWndOpened = FALSE;
		break;
	case PLB_ST_PLAY_MOV:
	//case PLB_ST_PAUSE_MOV:
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		// stop movie play
		//return UIFlowWndPlay_OnMovieFinish(pCtrl, paramNum, paramArray);
		return NVTEVT_CONSUME;
		break;
	case PLB_ST_PAUSE_MOV:
		UIFlowWndPlay_OnMovieFinish(pCtrl, paramNum, paramArray);

		SysSetFlag(FL_PROTECT, PROTECT_ONE);
		// Set Tab menu to Playback menu
		TM_SetMenu(&gPlaybackMenu);
		// Open common item menu
		Ux_OpenWindow(&MenuCommonItemCtrl, 0);
		g_bUIFlowWndPlayNoImgWndOpened = FALSE;
		break;
	}
	break;
    }

	return NVTEVT_CONSUME;
}

INT32 UIFlowWndPlay_OnChildClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
 UINT32 uiStatus;

    //#NT#2012/12/27#Hideo Lin -begin
    //#NT#Fix close child window hang up as card removed
    if(Ux_IsForceCloseWindow())
    {
        return NVTEVT_CONSUME;
    }
    //#NT#2012/12/27#Hideo Lin -end

    if(paramNum > 0)
    {
        //Return from thumbnail, magnify or delete mode and play current image again.
        switch(paramArray[0])
        {
        case NVTRET_THUMBNAIL:
        case NVTRET_MAGNIFY:
			// check whether card removed or not
		    if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED || (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE))
		    {
				if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
					if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED) {
						Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_2SEC);
					} else {
						Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORYERROR, FLOWWRNMSG_TIMER_KEEP);
					}
				}
			    break;
		    }
            UIPlay_PlaySingle(PB_SINGLE_CURR);
            FlowPB_UpdateIcons(1);
            UIFlowWndPlay_CheckStatus();
            break;
        case NVTRET_DELETE:
        case NVTRET_DELETEALL:
			// check whether card removed or not
		    if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED || (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE))
		    {
				if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
					if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED) {
						Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_2SEC);
					} else {
						Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORYERROR, FLOWWRNMSG_TIMER_KEEP);
					}
				}
			    break;
		    }
            uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);

            if (uiStatus & PB_STA_NOIMAGE)
            //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
            {
                if(!g_bUIFlowWndPlayNoImgWndOpened)
                {
                    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_IMAGE,FLOWWRNMSG_TIMER_KEEP);
                    g_bUIFlowWndPlayNoImgWndOpened = TRUE;
                }
            }
            else
            {
                UIPlay_PlaySingle(PB_SINGLE_CURR);
                FlowPB_UpdateIcons(1);
                UIFlowWndPlay_CheckStatus();
            }
            break;
        case NVTRET_ENTER_MENU:
            // Reset specific menu items
            SysSetFlag(FL_PROTECT, PROTECT_ONE);
            // Set Tab menu to Playback menu
            TM_SetMenu(&gPlaybackMenu);
            // Open common item menu
            Ux_OpenWindow(&MenuCommonItemCtrl, 0);
            g_bUIFlowWndPlayNoImgWndOpened = FALSE;
            break;
        case NVTRET_WARNING:
            Ux_PostEvent(paramArray[1], 0);
            break;
        }
    }
    else
    {
    	// check whether card removed or not
	    if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED || (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE))
	    {
			if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
				if (System_GetState(SYS_STATE_CARD)  == CARD_REMOVED) {
					Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_PLEASE_INSERT_SD, FLOWWRNMSG_TIMER_2SEC);
				} else {
					Ux_OpenWindow(&UIFlowWndWrnMsgCtrl, 2, UIFlowWndWrnMsg_StatusTXT_Msg_STRID_MEMORYERROR, FLOWWRNMSG_TIMER_KEEP);
				}
			}
			g_PlbData.State = PLB_ST_FULL;

		    //#NT#2012/10/23#Philex Lin - begin
		    // enable auto power off/USB detect timer
		    // enable sound key tone flag
		    KeyScan_EnableMisc(TRUE);
		    //#NT#2012/10/23#Philex Lin - end

		    // set mask key
		    //Ux_FlushEvent();
		    Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
		    Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
		    Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);
		    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
		    return NVTEVT_CONSUME;
	    }
        UIPlay_PlaySingle(PB_SINGLE_CURR);
        uiStatus = PB_WaitCommandFinish(PB_WAIT_INFINITE);
        if (uiStatus & PB_STA_NOIMAGE)
        //if(DCF_GetDBInfo(DCF_INFO_TOL_FILE_COUNT)==0)
        {
            if(!g_bUIFlowWndPlayNoImgWndOpened)
            {
                Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,FLOWWRNMSG_ISSUE_NO_IMAGE,FLOWWRNMSG_TIMER_KEEP);
                g_bUIFlowWndPlayNoImgWndOpened = TRUE;
            }
        }
        else
        {
            //UIPlay_PlaySingle(PB_SINGLE_CURR);
            FlowPB_UpdateIcons(1);
            UIFlowWndPlay_CheckStatus();
        }
    }
    g_PlbData.State = PLB_ST_FULL;

    //#NT#2012/10/23#Philex Lin - begin
    // enable auto power off/USB detect timer
    // enable sound key tone flag
    KeyScan_EnableMisc(TRUE);
    //#NT#2012/10/23#Philex Lin - end

    // set mask key
    //Ux_FlushEvent();
    Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
    Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
    Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);
    Ux_DefaultEvent(pCtrl,NVTEVT_CHILD_CLOSE,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBattery(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
  static volatile BOOL bBatteryOn = FALSE;

    UxState_SetData(&UIFlowWndPlay_StatusICN_BatteryCtrl,STATE_CURITEM,GetBatteryLevel());
    if (KeyScan_IsACIn())
    {
        bBatteryOn = !bBatteryOn;
        UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl,bBatteryOn);
    } else {
        UxCtrl_SetShow(&UIFlowWndPlay_StatusICN_BatteryCtrl,TRUE);
    }

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_OpenWindow(&UIFlowWndWrnMsgCtrl,2,UIFlowWndWrnMsg_StatusTXT_Msg_STRID_BATTERY_LOW, FLOWWRNMSG_TIMER_2SEC);
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyShutter2(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
		char   pFilePath[FULL_FILE_PATH_LEN];
		UINT32 uiPBFileFmt;
		UINT32 uiPBFileSize = 0;
CHKPNT;

		
	if (NVTEVT_KEY_RELEASE == paramArray[0]) {
		return NVTEVT_CONSUME;
	}

	switch (g_PlbData.State) {
		
	case PLB_ST_MAGNIFY:
		g_PlbData.State = PLB_ST_FULL;
		FlowPB_UpdateIcons(1);
		break;
	case PLB_ST_PLAY_MOV:
		CHKPNT;
			//Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_PAUSEPLAY, 0);
			ImageApp_MoviePlay_FilePlay_Pause();
            g_PlbData.State = PLB_ST_PAUSE_MOV;
            //FlowPB_IconDrawMovPlay(TRUE);
            //#NT#2012/10/23#Philex Lin - begin
            // enable auto power off/USB detect timer
            // enable sound key tone flag
            KeyScan_EnableMisc(TRUE);
            //#NT#2012/10/23#Philex Lin - end

            //Update UI
            FlowPB_IconDrawMovPlay(TRUE);
            FlowPB_IconDrawMovFwd(TRUE);
            FlowPB_IconDrawMovBwd(TRUE);
            break;
    case PLB_ST_PAUSE_MOV:
		CHKPNT;
            //#NT#2012/10/23#Philex Lin - begin
            // disable auto power off/USB detect timer
            // disable key tone flag
            KeyScan_EnableMisc(FALSE);
            //#NT#2012/10/23#Philex Lin - end
            // Start to Play
			//set movie volumn again to avoid volumn changed by beep sound
			Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
			ImageApp_MoviePlay_FilePlay_Resume();
            g_PlbData.State = PLB_ST_PLAY_MOV;
			FlowPB_IconDrawMovPlay(TRUE);
			FlowPB_IconDrawMovFwd(TRUE);
            FlowPB_IconDrawMovBwd(TRUE);
		break;
	
	case PLB_ST_FWD_MOV:
	case PLB_ST_BWD_MOV:
		//#NT#2012/10/23#Philex Lin - begin
        // disable auto power off/USB detect timer
        // disable key tone flag
        KeyScan_EnableMisc(FALSE);
        //#NT#2012/10/23#Philex Lin - end

		// Set to Normal Play
		g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
		UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
		g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

        // Start Play
        #if (NMEDIAPLAY_FUNC == DISABLE)
        ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURSPD, g_uiUIFlowWndPlayCurrenSpeed);
		ImageApp_MoviePlay_SetParam(MOVIEPLAY_PARAM_CURDIR, g_uiUIFlowWndPlayCurrenDirection);
		ImageApp_MoviePlay_UpdateAll();
		#else //(NMEDIAPLAY_FUNC == ENABLE)
		//UINT32 vdo_idx = AppDisp_MoviePlayView_GetDispIdx(); // get current display video index
		//ImageApp_MoviePlay_SetParam(MOVIEPLAY_NM_PARAM_DISP_IDX, vdo_idx);
		//ImageApp_MoviePlay_FilePlay_UpdateSpeedDirect(g_uiUIFlowWndPlayCurrenSpeed, g_uiUIFlowWndPlayCurrenDirection);
		#endif

        /*if (KeyScan_GetPlugDev()!=PLUG_HDMI)
        {
            FlowPB_IconDrawMovPlayVolumn(g_uiUIFlowWndPlayCurrentVolume);
        }*/
		
		//wanglong - begin 20181213
        //g_PlbData.State = PLB_ST_PLAY_MOV;
		ImageApp_MoviePlay_FilePlay_Pause();
        g_PlbData.State = PLB_ST_PAUSE_MOV;
        //#NT#2012/10/23#Philex Lin - begin
        // enable auto power off/USB detect timer
        // enable sound key tone flag
        KeyScan_EnableMisc(TRUE);
        //#NT#2012/10/23#Philex Lin - end

        //Update UI
        FlowPB_IconDrawMovPlay(TRUE);
        FlowPB_IconDrawMovFwd(TRUE);
        FlowPB_IconDrawMovBwd(TRUE);
		FlowPB_IconDrawMovSpeed();
		//wanglong - end

		break;
		
	case PLB_ST_FULL:
	default:
			debug_msg("<<<<<<<<<< <<<<<<<<<< <<<<<<<<<< PLB_ST_FULL \r\n");
			
			PB_GetParam(PBPRMID_CURR_FILEFMT, &uiPBFileFmt);
			if (uiPBFileFmt & (PBFMT_MOVMJPG | PBFMT_AVI | PBFMT_MP4 | PBFMT_TS)) {
                GXVIDEO_INFO VidInfo = {0};
                SMEDIAPLAY_MAX_MEM_INFO SMPMaxMemInfo = {0};

				// Open Video File
				if (gphUIFlowMovPlay_Filehdl) {
					FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
					gphUIFlowMovPlay_Filehdl = NULL;
				}
				if (uiPBFileFmt & PBFMT_TS) {
					PB_GetParam(PBPRMID_CURR_FILESIZE, &uiPBFileSize);
					if (uiPBFileSize <= 0x10000) {
						debug_msg("Wrong video file format!! \r\n");
						break;
					}
				}
				// Get Current index
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
				debug_msg("Play File Path = %s\r\n", pFilePath);
				
				//#NT#2017/11/13#Adam Su -begin
				//#NT#AUTO_TEST
				exam_msg("Play File Path = %s\r\n", pFilePath);
				//#NT#2017/11/13#Adam Su -end

				// Open Test Media File
				gphUIFlowMovPlay_Filehdl = FileSys_OpenFile(pFilePath, FST_OPEN_READ);

                if (!gphUIFlowMovPlay_Filehdl)
                {
                    debug_msg("UIFlowWndPlay_OnKeyEnter: Can't open Video file!\r\n");
                    break;
                }
                //#NT#2012/10/23#Philex Lin - begin
                // disable auto power off/USB detect timer
                // disable key tone flag
                KeyScan_EnableMisc(FALSE);
                //#NT#2012/10/23#Philex Lin - end

				UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
				g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

				ImageApp_Play_Close();
		

				#if (VDO_USE_COPY_BUFFER == ENABLE)
				VdoOut_SetSkipAllocTemp(TRUE);
				#endif

				// Config file play info
				gMovie_Play_Info.fileplay_id = _CFG_FILEPLAY_ID_1;
				gMovie_Play_Info.file_handle = gphUIFlowMovPlay_Filehdl;
				gMovie_Play_Info.curr_speed  = g_uiUIFlowWndPlayCurrenSpeed;
				gMovie_Play_Info.curr_direct = g_uiUIFlowWndPlayCurrenDirection;
				#if (NMEDIAPLAY_FUNC == DISABLE)
				gMovie_Play_Info.event_cb    = Play_MovieCB;
				#else //(NMEDIAPLAY_FUNC == ENABLE)
				gMovie_Play_Info.event_cb    = UIAppPlay_MoviePlayCB;
				#endif

                // Config max mem info
                PB_GetParam(PBPRMID_INFO_VDO, (UINT32*) &VidInfo);
                if (uiPBFileFmt & PBFMT_TS) {
                    SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_TS;
                } else if (uiPBFileFmt & PBFMT_MP4) {
                    SMPMaxMemInfo.FileFormat = MEDIA_FILEFORMAT_MOV;
                }
                SMPMaxMemInfo.VidFR = VidInfo.uiVidRate;
                SMPMaxMemInfo.AudFR = VidInfo.AudInfo.uiSR / 1024;
                SMPMaxMemInfo.TotalSecs = VidInfo.uiToltalSecs;
                SMPMaxMemInfo.CodecType = VidInfo.uiVidType;
                SMPMaxMemInfo.ImageWidth = VidInfo.uiVidWidth;
                SMPMaxMemInfo.ImageHeight = VidInfo.uiVidHeight;
                gMovie_Play_Info.pmax_mem_info = &SMPMaxMemInfo;

				ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_FILEPLAY_INFO, (UINT32) &gMovie_Play_Info);

				// Config rotation info
				UIFlowWndPlay_ConfigDispInfo();
                Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);

                //stop scan
                //SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, FALSE);
                SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, FALSE);

				ImageApp_MoviePlay_Open();
				#if (NMEDIAPLAY_FUNC == ENABLE)
				ImageApp_MoviePlay_Start();
				#endif
				//set movie volumn
				Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_MOVIEAUDPLAYVOLUME, 2, UI_GetData(FL_MovieAudioPlayIndex), 1);
				g_PlbData.State = PLB_ST_PLAY_MOV;
				FlowPB_IconDrawMovPlay(TRUE);
			} else {
				g_PlbData.State = PLB_ST_MAGNIFY;
				FlowPB_UpdateIcons(0);
				//#NT#2017/11/17#Adam Su -begin
				//#NT#AUTO_TEST
				PB_GetParam(PBPRMID_CURR_FILEPATH, (UINT32 *)pFilePath);
				exam_msg("Play File Path = %s\r\n", pFilePath);
				//#NT#2017/11/17#Adam Su -end
			}
			break;
		
		}
		

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnKeyPlayback(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    switch(g_PlbData.State)
    {
        case PLB_ST_FULL:
            // Set mask key
            Ux_FlushEventByRange(NVTEVT_KEY_EVT_START,NVTEVT_KEY_EVT_END);
            Input_SetKeyMask(KEY_PRESS, PLAY_KEY_PRESS_MASK);
            Input_SetKeyMask(KEY_RELEASE, PLAY_KEY_RELEASE_MASK);
            Input_SetKeyMask(KEY_CONTINUE, PLAY_KEY_CONTINUE_MASK);

            Ux_SendEvent(&UISetupObjCtrl,NVTEVT_EXE_CHANGEDSCMODE,1,DSCMODE_CHGTO_NEXT);
            break;

        case PLB_ST_PLAY_MOV:
        case PLB_ST_PAUSE_MOV:
        case PLB_ST_FWD_MOV:
        case PLB_ST_BWD_MOV:
            g_PlbData.State        = PLB_ST_FULL;
            g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
            UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
            g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

            Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_OPENPLAY, 0);
            Ux_SendEvent(&CustomMoviePlayObjCtrl, NVTEVT_EXE_CLOSEPLAY, 0);

            //#NT#2012/10/23#Philex Lin - begin
            // enable auto power off/USB detect timer
            // enable key tone flag
            KeyScan_EnableMisc(TRUE);
            //#NT#2012/10/23#Philex Lin - end

            if (gphUIFlowMovPlay_Filehdl)
            {
                FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
                gphUIFlowMovPlay_Filehdl = NULL;
            }
            FlowPB_UpdateIcons(1);
            break;

    }

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieFinish(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    //#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
    g_PlbData.State        = PLB_ST_FULL;
    g_PlbData.VideoPBSpeed = PLB_FWD_MOV_1x;
    UIFlowMoviePlay_SetSpeed(g_PlbData.VideoPBSpeed);
    g_uiUIFlowWndPlayCurrenDirection = SMEDIAPLAY_DIR_FORWARD;

	ImageApp_MoviePlay_Close();
	if (gMovie_Play_Info.event_cb) {
		#if (NMEDIAPLAY_FUNC == DISABLE)
		gMovie_Play_Info.event_cb(SMEDIAPLAY_EVENT_STOP); // release ISF_Data by AppDisp_ScaleView
		#else //((NMEDIAPLAY_FUNC == ENABLE))
		gMovie_Play_Info.event_cb(MOVIEPLAY_EVENT_STOP);
		#endif
	}

	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		return NVTEVT_CONSUME;
	}

	ImageApp_Play_Open();

	//#NT#2012/10/23#Philex Lin - begin
	// enable auto power off/USB detect timer
	// enable key tone flag
	KeyScan_EnableMisc(TRUE);
	//#NT#2012/10/23#Philex Lin - end

    // stop scan
    //if (SxTimer_GetFuncActive(SX_TIMER_DET_STRG_ID)==0)
//        SxTimer_SetFuncActive(SX_TIMER_DET_STRG_ID, TRUE);

    if (SxTimer_GetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID)==0)
        SxTimer_SetFuncActive(SX_TIMER_DET_SYSTEM_BUSY_ID, TRUE);


    if (gphUIFlowMovPlay_Filehdl)
    {
        FileSys_CloseFile(gphUIFlowMovPlay_Filehdl);
        gphUIFlowMovPlay_Filehdl = NULL;
    }

    // Play 1st video frame image
    UIPlay_PlaySingle(PB_SINGLE_CURR);
    //#NT#2012/08/31#Calvin Chang -end

    FlowPB_UpdateIcons(1);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    FlowPB_IconDrawMovPlayTime(TRUE);

    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
INT32 UIFlowWndPlay_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
#endif
	return NVTEVT_CONSUME;
}

//#NT#2012/08/31#Calvin Chang#Porting Media Flow -begin
void UIFlowMoviePlay_SetSpeed(INT16 uiChangeSpeedLevel)
{
    switch (uiChangeSpeedLevel)
    {
        default:
        case PLB_FWD_MOV_1x:
            g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_NORMAL;
        break;

        case PLB_FWD_MOV_2x:
        case PLB_BWD_MOV_2x:
            g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_2X;
        break;

        case PLB_FWD_MOV_4x:
        case PLB_BWD_MOV_4x:
            g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_4X;
        break;

        case PLB_FWD_MOV_8x:
        case PLB_BWD_MOV_8x:
            g_uiUIFlowWndPlayCurrenSpeed = SMEDIAPLAY_SPEED_8X;
        break;

    }
}
//#NT#2012/08/31#Calvin Chang -end
static void UIFlowWndPlay_SetDispParam(MOVIEPLAY_DISP_INFO *p_disp_info, BOOL en)
{
	USIZE device_ratio, src_size;

	if (en == TRUE) { // use dev_id when enable
		device_ratio = GxVideo_GetDeviceAspect(p_disp_info->dev_id);
	} else {
		device_ratio = GxVideo_GetDeviceAspect(DOUT1);
	}
	PB_GetParam(PBPRMID_SRC_SIZE, (UINT32 *) &src_size); // get source image size from playback

	p_disp_info->enable			= en;
	p_disp_info->width			= src_size.w;
	p_disp_info->height			= src_size.h;
	p_disp_info->width_ratio	= device_ratio.w;
	p_disp_info->height_ratio	= device_ratio.h;
	p_disp_info->rotate_dir		= SysVideo_GetDirbyID(p_disp_info->dev_id);

	ImageApp_MoviePlay_Config(MOVIEPLAY_CONFIG_DISP_INFO, (UINT32)p_disp_info);
}

void UIFlowWndPlay_ConfigDispInfo(void)
{
	//MOVIEPLAY_DISP_INFO	*p_disp_info = NULL;

#if (DISPLAY2_FUNC == ENABLE)
	if (g_DualVideo == DISPLAY_1) {
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], TRUE);
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_2], FALSE);
	} else if (g_DualVideo == DISPLAY_2) {
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], FALSE);
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_2], TRUE);
	} else if (g_DualVideo == (DISPLAY_1|DISPLAY_2)) {
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], TRUE);
		UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_2], TRUE);
	}
#else
	UIFlowWndPlay_SetDispParam(&gUIFlowWndPlayDispConfig[UIFLOW_PLAY_DISP_ID_1], TRUE);
#endif

}

//----------------------UIFlowWndPlay_StaticICN_DSCModeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_DSCMode)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_FlashCtrl Event---------------------------
INT32 UIFlowWndPlay_StatusICN_Flash_OnKeyRight(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Flash)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIFlowWndPlay_StatusICN_Flash_OnKeyRight)
EVENT_END

INT32 UIFlowWndPlay_StatusICN_Flash_OnKeyRight(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_SendEvent(pCtrl,NVTEVT_NEXT_ITEM,0);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlay_StatusICN_EVCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_EV)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_SizeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Size)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_WBCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_WB)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_QualityCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Quality)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_SharpnessCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Sharpness)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_StorageCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Storage)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_BatteryCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Battery)
EVENT_END

//----------------------UIFlowWndPlay_TabHistogramCtrl Event---------------------------
INT32 UIFlowWndPlay_TabHistogram_OnRedraw(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_TabHistogram)
EVENT_ITEM(NVTEVT_REDRAW,UIFlowWndPlay_TabHistogram_OnRedraw)
EVENT_END

INT32 UIFlowWndPlay_TabHistogram_OnRedraw(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    Ux_DefaultEvent(pCtrl,NVTEVT_REDRAW,paramNum,paramArray);
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlay_StaticTXT_FilenameCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Filename)
EVENT_END

//----------------------UIFlowWndPlay_StaticICN_ProtectCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_Protect)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_DateCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Date)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_TimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Time)
EVENT_END

//----------------------UIFlowWndPlay_HistoCtrl Event---------------------------
INT32 UIFlowWndPlay_Histo_OnRedraw(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIFlowWndPlay_Histo)
EVENT_ITEM(NVTEVT_REDRAW,UIFlowWndPlay_Histo_OnRedraw)
EVENT_END

INT32 UIFlowWndPlay_Histo_OnRedraw(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
    return NVTEVT_CONSUME;
}
//----------------------UIFlowWndPlay_StatusICN_MovPlayCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_MovPlay)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_MovStopCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_MovStop)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_MovBwdCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_MovBwd)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_MovPlayTimeCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_MovPlayTime)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_MovFwdCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_MovFwd)
EVENT_END

//----------------------UIFlowWndPlay_StatusICN_VolumnCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StatusICN_Volumn)
EVENT_END

//----------------------UIFlowWndPlay_StaticICN_PrintCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticICN_Print)
EVENT_END

//----------------------UIFlowWndPlay_StaticTXT_SpeedCtrl Event---------------------------
EVENT_BEGIN(UIFlowWndPlay_StaticTXT_Speed)
EVENT_END

