//This source code is generated by UI Designer Studio.

#include "stdio.h"
#include "UIFramework.h"
#include "UIFrameworkExt.h"
#include "NVTToolCommand.h"
#include "UIMenuWndWiFiMobileLinkOKRes.c"
#include "WifiAppCmd.h"
#include "UIFlow.h"
#include "UIAppNetwork.h"
#include "GSensor.h"
#include "ImageApp_MovieMulti.h"
#include "UIMenuWndWiFiMobileLinkOKIcons.h"
#include "UIAppWiFiCmdMovie.h"
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
#include "ImageApp_UsbMovie.h"
#include "ImageUnit_UsbUVAC.h"
#include "UsbCmdAPI.h"
#endif
//#NT#2016/05/31#Ben Wang -end
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Debug Definition -----------------------------
#define _UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG        1
#define _UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG        1

#if (_UIMENUWNDWIFIMOBILELINKOK_ERROR_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_ERR))
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)            debug_msg ("^R UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKErrMsg(...)
#endif

#if (_UIMENUWNDWIFIMOBILELINKOK_TRACE_MSG&(PRJ_DBG_LVL>=PRJ_DBG_LVL_TRC))
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)          debug_msg ("^B UIMenuWndWiFiMobileLinkOK: "__VA_ARGS__)
#else
#define UIMenuWndWiFiMobileLinkOKTraceMsg(...)
#endif

extern BOOL MCUSendAT_SOS;
extern BOOL RecvCMD_WIFI_OFF;
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Global Variables -----------------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Prototype Declaration  -----------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Public API  ----------------------------------

//---------------------UIMenuWndWiFiMobileLinkOKCtrl Private API  ---------------------------------
//---------------------UIMenuWndWiFiMobileLinkOKCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Button_Disconnect)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticTXT_MAC)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_CyclicRec)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_battery)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_YMD_Static)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_HMS_Static)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Panel)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Status_Storage)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_time)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_maxtime)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_resolution)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StatusICN_EV)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StatusWIFILink)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK__StatusICN_WB)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StatusICN_ISO)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StatusICN_Selftimer)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticTXT_FreePic)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticTXT_Size)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StatusICN_Quality)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK__StaticICN_Protect)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_Static_camera)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticICN_DSCMode)
CTRL_LIST_ITEM(UIMenuWndWiFiMobileLinkOK_StaticI_PlayMode)
CTRL_LIST_END
char StringTmpBuf[32] = {0};
//----------------------UIMenuWndWiFiMobileLinkOKCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_DHCP_REQ(VControl *, UINT32, UINT32 *);

INT32 UIMenuWndWiFiModuleLinkOK_OnStorageInit(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiModuleLinkOK_OnStorageChange(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeChangeModeDone(VControl *, UINT32, UINT32 *);

INT32 UIMenuWndWiFiMobileLinkOK_OnCustom1(VControl *, UINT32, UINT32 *);
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieTriggerRawEnc(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray);
INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *, UINT32, UINT32 *);

EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK)
EVENT_ITEM(NVTEVT_OPEN_WINDOW, UIMenuWndWiFiMobileLinkOK_OnOpen)
EVENT_ITEM(NVTEVT_CLOSE_WINDOW, UIMenuWndWiFiMobileLinkOK_OnClose)
EVENT_ITEM(NVTEVT_WIFI_AUTHORIZED_OK, UIMenuWndWiFiMobileLinkOK_Authorized_OK)
EVENT_ITEM(NVTEVT_WIFI_DHCP_REQ, UIMenuWndWiFiMobileLinkOK_DHCP_REQ)


EVENT_ITEM(NVTEVT_STORAGE_INIT, UIMenuWndWiFiModuleLinkOK_OnStorageInit)
EVENT_ITEM(NVTEVT_STORAGE_CHANGE, UIMenuWndWiFiModuleLinkOK_OnStorageChange)
EVENT_ITEM(NVTEVT_BACKGROUND_DONE, UIMenuWndWiFiMobileLinkOK_OnBackgroundDone)
EVENT_ITEM(NVTEVT_CB_MOVIE_OVERTIME, UIMenuWndWiFiMobileLinkOK_OnMovieFull) // the same handling as storage full (may need to show special message)
EVENT_ITEM(NVTEVT_CB_MOVIE_FULL, UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_LOOPREC_FULL, UIMenuWndWiFiMobileLinkOK_OnMovieFull)
EVENT_ITEM(NVTEVT_CB_MOVIE_WR_ERROR, UIMenuWndWiFiMobileLinkOK_OnMovieWrError)
EVENT_ITEM(NVTEVT_CB_MOVIE_SLOW, UIMenuWndWiFiMobileLinkOK_OnStorageSlow)
EVENT_ITEM(NVTEVT_CB_MOVIE_REC_ONE_SEC, UIMenuWndWiFiMobileLinkOK_OnMovieOneSec)
EVENT_ITEM(NVTEVT_CB_RAWENC_OK, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB)
EVENT_ITEM(NVTEVT_CB_RAWENC_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_WRITE_ERR, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_CB_RAWENC_DCF_FULL, UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr)
EVENT_ITEM(NVTEVT_BATTERY_LOW, UIMenuWndWiFiMobileLinkOK_OnBatteryLow)
EVENT_ITEM(NVTEVT_WIFI_DEAUTHENTICATED, UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated)
EVENT_ITEM(NVTEVT_CB_MOVIE_VEDIO_READY, UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady)
EVENT_ITEM(NVTEVT_KEY_CUSTOM1,UIMenuWndWiFiMobileLinkOK_OnCustom1)
EVENT_ITEM(NVTEVT_KEY_RIGHT,UIMenuWndWiFiMobileLinkOK_OnExeMovieTriggerRawEnc)
EVENT_ITEM(NVTEVT_TIMER, UIMenuWndWiFiMobileLinkOK_OnTimer)
EVENT_END

//#if (OPEN_WIFI_AUTO_RECORDING == ENABLE)
extern bool bAutoRecordEn;
//#endif
extern char gLastMacAddr[];
INT32 UIMenuWndWiFiMobileLinkOK_OnOpen(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	static char Buf1[32] = {0};//, buf2[32] = {0} ;

	Ux_FlushEventByRange(NVTEVT_KEY_EVT_START, NVTEVT_KEY_EVT_END);
	Input_SetKeyMask(KEY_PRESS, FLGKEY_KEY_MASK_DEFAULT);
	Input_SetKeyMask(KEY_RELEASE, 0);
	Input_SetKeyMask(KEY_CONTINUE, 0);
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		if (ImageUnit_GetParam(&ISF_UsbUVAC, IMGUNIT_UVAC_CFG_CDC_ENABLE)) {
			MEM_RANGE WorkBuf;
			WorkBuf.Addr = OS_GetMempoolAddr(POOL_ID_USBCMD);
			WorkBuf.Size = POOL_SIZE_USBCMD;
			UsbCmd_Open(&WorkBuf);
		}
		snprintf(Buf1, sizeof(Buf1), "UVC Connected");
		//just don't show this string
		StringTmpBuf[0] = 0;
	} else
#endif
	{
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
		snprintf(Buf1, sizeof(Buf1), "WiFi Connected");
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), "MAC:%s", UINet_GetConnectedMAC());
#else
		snprintf(Buf1, sizeof(Buf1), "Ethernet Connected");
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), " IP : %s", UINet_GetIP());
#endif
	}
//#NT#2016/05/31#Ben Wang -end
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_LinkStsCtrl, STATIC_VALUE, Txt_Pointer(Buf1));
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));

	//snprintf(buf2, sizeof(buf2), "Press Enter to Close WIFI");
	//UxButton_SetItemData(&UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl, 0, BTNITM_STRID, Txt_Pointer(buf2));

	UIMenuWndWiFiMobileLinkOK_UpdatePhotoIcons(FALSE);
 	UIMenuWndWiFiMobileLinkOK_UpdateMoiveIcons(TRUE,TRUE);
	
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) != SYS_SUBMODE_UVC)
#endif
	{
		//make sure, connec to RTSP mode
		if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
			Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
		}
	}
//#NT#2016/05/31#Ben Wang -end
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	WiFiCmd_HBStart();
#endif
//#NT#2016/03/23#Isiah Chang -end
	WiFiCmd_MotionDetectStart();
	WiFiCmd_UIUpdateStart();//
       WifiCmd_ReceiveCmd(TRUE);

	Ux_DefaultEvent(pCtrl, NVTEVT_OPEN_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnClose(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	if (UI_GetData(FL_MOVIE_SIZE_MENU) != UI_GetData(FL_MOVIE_SIZE)) {
		Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIESIZE, 1, UI_GetData(FL_MOVIE_SIZE_MENU));
	}
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	WiFiCmd_HBStop();
#endif
//#NT#2016/03/23#Isiah Chang -end
	WiFiCmd_MotionDetectStop();
	WifiCmd_ReceiveCmd(FALSE);
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	//if(System_GetState(SYS_STATE_CURRSUBMODE)==SYS_SUBMODE_UVC && System_GetState(SYS_STATE_NEXTSUBMODE)!=SYS_SUBMODE_UVC)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		if (ImageUnit_GetParam(&ISF_UsbUVAC, IMGUNIT_UVAC_CFG_CDC_ENABLE)) {
			UsbCmd_Close();
		}
	}
#endif
//#NT#2016/05/31#Ben Wang -end
	Ux_DefaultEvent(pCtrl, NVTEVT_CLOSE_WINDOW, paramNum, paramArray);
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_Authorized_OK(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

	UINT32 bNewUser = 0 ;
	if (paramNum) {
		bNewUser = paramArray[0];
	}
#if 0  //print MAC when client get IP
	snprintf(StringTmpBuf, sizeof(StringTmpBuf), " MAC : %s", UINet_GetConnectedMAC());
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#endif
	if (bNewUser) {
		//delay 500 ms,disconnect last user and
		//in window,use GxTimer replace Timer Delay,it would occupat UI task
		GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DISCONNECT_LAST_TIMER, ONE_SHOT);
	}
	snprintf(StringTmpBuf, sizeof(StringTmpBuf), "MAC:%s", UINet_GetConnectedMAC());
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#if 0 // Moved to UINet_DhcpSrvCBCliConn.
	//make sure, connec to RTSP mode
	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE) {
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 1, PRIMARY_MODE_MOVIE);
	}
#endif

	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_DHCP_REQ(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	char *pMAC = 0;
	if (paramNum) {
		pMAC = (char *)paramArray[0];
	}
	//#NT#2016/12/27#YongChang Qui -begin
	//#NT#don't display mac address on UI if mac is 0:0:0:0:0:0:0
	if (pMAC && (pMAC[0] || pMAC[1] || pMAC[2] || pMAC[3] || pMAC[4] || pMAC[5]))
		//#NT#2016/12/27#YongChang Qui -end
	{
		snprintf(StringTmpBuf, sizeof(StringTmpBuf), "MAC:%02x%02x%02x%02x%02x%02x", pMAC[0], pMAC[1], pMAC[2]\
				 , pMAC[3], pMAC[4], pMAC[5]);
		UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiModuleLinkOK_OnStorageInit(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	if (UIStorageCheck(STORAGE_CHECK_ERROR, NULL) == TRUE) {
		UIMenuWndWiFiMobileLinkOKTraceMsg("card err,removed\r\n");
	} else {
		UIMenuWndWiFiMobileLinkOKTraceMsg("card insert\r\n");
		if (System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PLAYBACK) {
			Ux_SendEvent(0, NVTEVT_SYSTEM_MODE, 1, System_GetState(SYS_STATE_CURRMODE));
		} else {
			ImageUnit_SetParam(&ISF_CamFile, CAMFILE_PARAM_FILEDB_REOPEN, 0);
		}
		WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_CARD_INSERT);
	}
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiModuleLinkOK_OnStorageChange(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
#if (SDHOTPLUG_FUNCTION == ENABLE)
	UIMenuWndWiFiMobileLinkOKTraceMsg("card removed\r\n");
	if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_PLAYBACK) {
		ImageUnit_SetParam(&ISF_CamFile, CAMFILE_PARAM_FILEDB_CLOSE, 0);
	}
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_CARD_REMOVE);
#endif
	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnBackgroundDone(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	NVTEVT event;
	UINT32 status;

	event = paramArray[ONDONE_PARAM_INDEX_CMD];
	status = paramArray[ONDONE_PARAM_INDEX_RET];
	debug_err(("%s event = 0x%x, status=%d\r\n", __FUNCTION__, event, status));

	switch (event) {
	case NVTEVT_BKW_FORMAT_CARD: {
			WifiCmd_Done(WIFIFLAG_FORMAT_DONE, WIFIAPP_RET_OK);
			//Rsvd
			break;
		}

	case NVTEVT_BKW_FORMAT_NAND: {
			WifiCmd_Done(WIFIFLAG_FORMAT_DONE, WIFIAPP_RET_OK);
			//Rsvd
			break;
		}

	case NVTEVT_BKW_FW_UPDATE: {
			if (status) {
				debug_err(("%s:update FW fail %d\r\n", __FUNCTION__, status));
				WifiCmd_Done(WIFIFLAG_UPDATE_DONE, status + WIFIAPP_RET_FW_OFFSET);
			} else {
				//#NT#2016/03/23#Isiah Chang -begin
				//#NT#add new Wi-Fi UI flow.
				INT32 ret;

				WifiCmd_Done(WIFIFLAG_UPDATE_DONE, WIFIAPP_RET_OK);

				ret = FileSys_DeleteFile(FW_UPDATE_NAME);
				if (ret != FST_STA_OK) {
					debug_err(("%s:delete FW fail %d\r\n", __FUNCTION__, status));
				}
				//#NT#2016/03/23#Isiah Chang -end
				Delay_DelayMs(2000);
				// Should power off immediatelly
				System_PowerOff(SYS_POWEROFF_NORMAL);
			}
			break;
		}

	default:
		debug_err(("%s:Unknown event 0x%x\r\n", __FUNCTION__, event));
		break;
	}
	return NVTEVT_CONSUME;
}

INT32 UIMenuWndWiFiMobileLinkOK_OnMovieFull(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Card Full");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));
	return WiFiCmd_OnMovieFull(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieWrError(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Card Error");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	return WiFiCmd_OnMovieWrError(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnStorageSlow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Slow Card");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	return WiFiCmd_OnStorageSlow(pCtrl, paramNum, paramArray);
}
INT32 UIMenuWndWiFiMobileLinkOK_OnMovieOneSec(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnMovieOneSec(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncJpgOKCB(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnMovieRawEncJpgOKCB(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieRawEncErr(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnMovieRawEncErr(pCtrl, paramNum, paramArray);
}

INT32 UIMenuWndWiFiMobileLinkOK_OnBatteryLow(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UIMenuWndWiFiMobileLinkOKTraceMsg("%s \r\n", __FUNCTION__);

	//snprintf(StringTmpBuf,sizeof(StringTmpBuf),"Battery Low");
	//UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl,STATIC_VALUE,Txt_Pointer(StringTmpBuf));

	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_BATTERY_LOW);
	return NVTEVT_CONSUME;
}


INT32 UIMenuWndWiFiMobileLinkOK_OnCustom1(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{

	UINT32 CrashTime = 20;
#if 0
    UINT32  uiWidth  = GetMovieSizeWidth(UI_GetData(FL_MOVIE_SIZE));

    if(SysGetFlag(FL_GSENSOR) !=GSENSOR_OFF)
    {
        if ( (gMovData.State == MOV_ST_REC) || (gMovData.State == MOV_ST_REC_WAIT) )
        {
            if (SysGetFlag(FL_MOVIE_URGENT_PROTECT_AUTO)==MOVIE_URGENT_PROTECT_AUTO_ON)
            {
#if (MOVIE_MULTI_RECORD_FUNC)
                if(GetMovieRecType_2p(UI_GetData(FL_MOVIE_SIZE))==MOVIE_REC_TYPE_DUAL
                    || GetMovieRecType_2p(UI_GetData(FL_MOVIE_SIZE))==MOVIE_REC_TYPE_CLONE)
                {
                   debug_err(("dual record, not support urgent protect !\r\n"));
                   return NVTEVT_CONSUME;
                }
#endif
                if ((uiWidth <= 1920) && (UI_GetData(FL_MOVIE_CYCLIC_REC) != MOVIE_CYCLICREC_OFF))
                {
                    DBG_DUMP("process flash video record!!!\r\n");
                    MovRec_StopFlash(0);
                }
                else
                {
                    DBG_DUMP("Set Crash!!!\r\n");
			debug_msg("Set Crash-yxf_debug\r\n");		
                    MovRec_SetCrash();
                }
            }

        }
    }
	#endif
	#if 1
	if(paramArray[0]==NVTEVT_KEY_PRESS)
    	{
		if (WiFiCmd_GetStatus() == WIFI_MOV_ST_RECORD) 
		{
			if (SysGetFlag(FL_MOVIE_URGENT_PROTECT_AUTO) == MOVIE_URGENT_PROTECT_AUTO_ON) 
			{
				debug_msg("Set Crash-_debug\r\n");	
				switch(SysGetFlag(FL_MOVIE_CYCLIC_REC))
				{
                       		case MOVIE_CYCLICREC_1MIN:
                          		 CrashTime = 60-1;
						   break;
					case MOVIE_CYCLICREC_3MIN:
                           			CrashTime = 60*3-1;
						   break;
					case MOVIE_CYCLICREC_5MIN:
                         			CrashTime = 60*5-1;
						   break; 	   
					case MOVIE_CYCLICREC_10MIN:
                         			CrashTime = 60*10-1;
						   break; 	 
					case MOVIE_CYCLICREC_OFF:
                         			CrashTime = 60*10-1;
						   break; 		   
				}
				//UxCtrl_SetShow(&UIFlowWndMovie_StaticICN_ProtectCtrl, TRUE);
				UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK__StaticICN_ProtectCtrl, TRUE);
				ImageApp_MovieMulti_SetParam(_CFG_REC_ID_1,MOVIEMULTI_PARAM_FILE_ROLLBACKSEC_CRASH,CrashTime);
				ImageApp_MovieMulti_SetCrash(_CFG_REC_ID_1, TRUE);
				MCUSendAT_SOS = FALSE;
			}
		}
    	}
	#endif

	 
    return NVTEVT_CONSUME;
}




//lÂ¼ÏñÖÐÅÄÕÕ
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieTriggerRawEnc(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
    UINT32 result = 0;
    //UINT32 curStatus = 0;
    UINT32 uiJpegWidth, uiJpegHeight, uiDAR, uiMovieSize;

    if (System_GetState(SYS_STATE_CURRMODE) != PRIMARY_MODE_MOVIE)
    {
        return NVTEVT_CONSUME;
    }
    //curStatus = UIFlowWndWiFiMovie_GetStatus();
   // if(MovRec_IsRecording())//curStatus == WIFI_MOV_ST_RECORD)
    if(WIFI_MOV_ST_RECORD == WiFiCmd_GetStatus())
    {
        uiMovieSize = UI_GetData(FL_MOVIE_SIZE);
        uiJpegWidth = GetMovieSizeWidth(uiMovieSize);
        uiJpegHeight = GetMovieSizeHeight(uiMovieSize);
        uiDAR = GetMovieDispAspectRatio(uiMovieSize);
        /*
        if (uiDAR == VIDENC_DAR_16_9)
        {
            uiJpegWidth = (uiJpegHeight * 16) / 9;
        }
        */
        Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_REC_RAWENC, 2, uiJpegWidth, uiJpegHeight);
    }
    else
    {
        result = -1;
        debug_msg("Not in recording state\r\n");
    }
    return NVTEVT_CONSUME;	
}



INT32 UIMenuWndWiFiMobileLinkOK_OnDeAuthenticated(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	CHKPNT;
//#NT#2016/03/23#Isiah Chang -begin
//#NT#add new Wi-Fi UI flow.
#if (WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
#else
	snprintf(StringTmpBuf, sizeof(StringTmpBuf), "No connect");
	UxStatic_SetData(&UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl, STATIC_VALUE, Txt_Pointer(StringTmpBuf));
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	UINet_CliReConnect(1);
#endif
#endif
//#NT#2016/03/23#Isiah Chang -end
	return NVTEVT_CONSUME;

	//Ux_CloseWindow(pCtrl,0);

	return NVTEVT_CONSUME;
}
INT32 UIMenuWndWiFiMobileLinkOK_OnExeMovieVedioReady(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	return WiFiCmd_OnExeMovieVedioReady(pCtrl, paramNum, paramArray);
}
extern BOOL CurrentRateBeforWIFI_onFlag;
INT32 UIMenuWndWiFiMobileLinkOK_OnTimer(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
	UINT32  uiEvent;
	uiEvent = paramNum ? paramArray[0] : 0;

	switch (uiEvent) {
	case NVTEVT_DISCONNECT_LAST_TIMER:
		UINet_AddACLTable();
		return NVTEVT_CONSUME;
	case NVTEVT_DELAY_CLOSE_TIMER:
		{
			//#NT#2016/03/08#Niven Cho -begin
			//#NT#because it is long time closing the linux-wifi, we don't change mode to movie video ahead.
			//#NT#use Ux_SendEvent(0,NVTEVT_EXE_WIFI_STOP, 0),not post event
			#if (WIFI_FUNC == ENABLE)
					 if(CurrentRateBeforWIFI_onFlag == TRUE)
				     	{
				     		CurrentRateBeforWIFI_onFlag = FALSE;
				     		Ux_SendEvent(&CustomMovieObjCtrl, NVTEVT_EXE_MOVIE_RATE_SET, 1, MOVIE_RATE_HIGH);
					       Delay_DelayMs(100);
				     	}
					Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, PRIMARY_MODE_MOVIE, SYS_SUBMODE_NORMAL);
					//should close network application,then stop wifi
					Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);
					SysSetFlag(FL_WIFI,WIFI_OFF);
					bAutoRecordEn = FALSE;
			#endif
			//#NT#2016/03/08#Niven Cho -end
			return NVTEVT_CONSUME;
		}

//#NT#2017/01/03#Isiah Chang -begin
//#NT#Add WiFiCmd Bitrate control.
#if(WIFI_UI_FLOW_VER == WIFI_UI_VER_2_0)
	case NVTEVT_1SEC_TIMER: {
			WiFiCmd_HBOneSec();
			return NVTEVT_CONSUME;
		}
#endif
//#NT#2017/01/03#Isiah Chang -end
	case NVTEVT_05SEC_TIMER: {
			WiFiCmd_OnMotionDetect();
			return NVTEVT_CONSUME;
		}
	case NVTEVT_1SEC_TIMER: {
		if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE)
		{
			if ((WiFiCmd_GetStatus() == WIFI_MOV_ST_RECORD) && (FlowMovie_GetRecCurrTime() >= 1))
			{
				//FlowMovieWifi_IconDrawRec(&UIMenuWndWiFiMobileLinkOK_PanelCtrl);
				UxCtrl_SetShow(&UIMenuWndWiFiMobileLinkOK_PanelCtrl,!UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_PanelCtrl));
				FlowMovieWifi_IconHideMaxRecTime(&UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl);
				FlowMovieWifi_IconDrawRecTime(&UIMenuWndWiFiMobileLinkOK_Static_timeCtrl);
			}
			else
			{
				FlowMovieWifi_IconHideRec(&UIMenuWndWiFiMobileLinkOK_PanelCtrl);
				FlowMovieWifi_IconHideRecTime(&UIMenuWndWiFiMobileLinkOK_Static_timeCtrl);
				FlowMovieWifi_IconDrawMaxRecTime(&UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl);
			}
		}

		if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_MOVIE)
		{
			FlowMovieWifi_IconDrawDateTime();
			UIMenuWndWiFiMobileLinkOK_UpdateMoiveIcons(TRUE,FALSE);
		}
		else if(System_GetState(SYS_STATE_CURRMODE) == PRIMARY_MODE_PHOTO)
		{
			UIMenuWndWiFiMobileLinkOK_UpdatePhotoIcons(TRUE);
		}
		
		//if (UxCtrl_IsShow(&UIMenuWndWiFiMobileLinkOK_StaticIcon_PIMCCtrl))
		//	FlowMovieWifi_DrawPIM(FALSE);
		return NVTEVT_CONSUME;
	}
	default:
		return NVTEVT_CONSUME;
	}
}





//----------------------UIMenuWndWiFiMobileLinkOK_Button_DisconnectCtrl Event---------------------------
INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter(VControl *, UINT32, UINT32 *);
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Button_Disconnect)
EVENT_ITEM(NVTEVT_KEY_SELECT, UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter)
EVENT_END

INT32 UIMenuWndWiFiMobileLinkOK_Button_Disconnect_OnKeyEnter(VControl *pCtrl, UINT32 paramNum, UINT32 *paramArray)
{
CHKPNT;
//#NT#2016/05/31#Ben Wang -begin
//#NT#Add UVC multimedia function.
#if(UVC_MULTIMEDIA_FUNC == ENABLE)
	if (System_GetState(SYS_STATE_CURRSUBMODE) == SYS_SUBMODE_UVC) {
		Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
		return NVTEVT_CONSUME;
	}
#endif
//#NT#2016/05/31#Ben Wang -end
#if (WIFI_FUNC == ENABLE)
#if !defined(_NVT_SDIO_WIFI_NONE_) || !defined(_NVT_USB_WIFI_NONE_)
	//notify current connected socket,new connect not get IP and socket not create
	//cannot disconnet immediate,suggest after 500 ms
	CHKPNT;
	WifiApp_SendCmd(WIFIAPP_CMD_NOTIFY_STATUS, WIFIAPP_RET_DISCONNECT);
	//delay 500 ms,and then close window
	//in window,use GxTimer replace Timer Delay,it would occupat UI task
	GxTimer_StartTimer(TIMER_HALF_SEC, NVTEVT_DELAY_CLOSE_TIMER, ONE_SHOT);
#else

	Ux_PostEvent(NVTEVT_SYSTEM_MODE, 2, System_GetState(SYS_STATE_CURRMODE), SYS_SUBMODE_NORMAL);
	//should close network application,then stop wifi
	Ux_PostEvent(NVTEVT_EXE_WIFI_STOP, 0);

#endif
#endif
	return NVTEVT_CONSUME;
}
//----------------------UIMenuWndWiFiMobileLinkOK_StaticTXT_MACCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticTXT_MAC)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_CyclicRecCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_CyclicRec)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_batteryCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_battery)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_YMD_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_YMD_Static)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_HMS_StaticCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_HMS_Static)
EVENT_END

//---------------------UIMenuWndWiFiMobileLinkOK_PanelCtrl Control List---------------------------
CTRL_LIST_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel)
CTRL_LIST_END

//----------------------UIMenuWndWiFiMobileLinkOK_PanelCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Panel)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Status_StorageCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Status_Storage)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_timeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_time)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_maxtimeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_maxtime)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_resolutionCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_resolution)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StatusICN_EVCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StatusICN_EV)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StatusWIFILinkCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StatusWIFILink)
EVENT_END


//----------------------UIMenuWndWiFiMobileLinkOK__StatusICN_WBCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK__StatusICN_WB)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StatusICN_ISOCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StatusICN_ISO)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StatusICN_SelftimerCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StatusICN_Selftimer)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StaticTXT_FreePicCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticTXT_FreePic)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StaticTXT_SizeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticTXT_Size)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StatusICN_QualityCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StatusICN_Quality)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK__StaticICN_ProtectCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK__StaticICN_Protect)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_Static_cameraCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_Static_camera)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StaticICN_DSCModeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticICN_DSCMode)
EVENT_END

//----------------------UIMenuWndWiFiMobileLinkOK_StaticI_PlayModeCtrl Event---------------------------
EVENT_BEGIN(UIMenuWndWiFiMobileLinkOK_StaticI_PlayMode)
EVENT_END

