/*;   Copyright   Novatek Microelectronics Corp. 2012.  All rights reserved.
 *;
 *;   @file       BinInfo.c
 *;   @ingroup
 *;
 *;   @brief      Binary file information
 *;               Binary file information
 *;
 *;   @version    V1.20.000
 *;   @author     Novatek
 *;   @date       2012/07/19
 */
#include <nvt_type.h>
#include <generated/version_autogenerated.h>
#include <modelext/bin_info.h>

#define __string(_x) #_x
#define __xstring(_x) __string(_x)

extern char _start_nvt;

extern HEADINFO gHeadInfo __attribute__ ((section (".data.bininfo")));
HEADINFO gHeadInfo =
{
	(UINT32)&_start_nvt, //<- fw CODE entry (4)
	{0}, ///<- reserved (4*19)
	"ub51023 ", //<- CHIP-NAME / TAG-NAME (8)
	NVT_VERSION_STRING, //<- version (8)
	__xstring(_BUILD_DATE_), //<- releasedate (8)
	0xffffffff, //<- Bin File Length (4)
	0xffffffff, //<- Check Sum or CRC (4)
	0,///<- Length check for CRC (4)
	0,///<- where modelext data is. w by Ld / u-boot (4)
	0,
	0,///<- Binary Tag for CRC (4)
};

extern char gBinEnd[4] __attribute__ ((section (".BinEnd")));
char gBinEnd[4] =
{'_','E','N','D'};
